### ISSUE TITLE
Whether to consider supporting EndpointSlices of v1beta1 version？

### ISSUE THREAD

**Issue by zcz-1020** [submariner-io/lighthouse#1040]
Previous [issues,](https://github.com/submariner-io/lighthouse/issues/576) assuming no longer need to support versions before 1.20. However, there are 1.19 clusters in practice. Can we consider supporting 1.19 K8s?

**Comment by skitt** [comment]
I doubt we’d implement this; if you want to work on it, feel free, but the support would have to be cleanly encapsulated.

**Comment by zcz-1020** [comment]
ok, I see.

**Comment by dfarrell07** [comment]
@zcz-1020 I'm assuming that means this can be closed? If not, if you're planning on working on this, feel free to reopen!
