### ISSUE TITLE
Service address is resolved from the local cluster while readiness probe is not healthy yet

### ISSUE THREAD

**Issue by MartijnStraatman** [submariner-io/lighthouse#1090]
**What happened**:

We have two exported services. As soon as the pod starts and it waits for the readiness probe to be healthy the local service address is resolved. Since the pod is not ready yet no traffic is routed to the pod. It will time out.

**What you expected to happen**:
I expected it to failover to the other cluster which has exported the service. That pod is healthy.

If we look at the endpoints

when all is `ok`

```bash
$ kubectl get endpoints
NAME                  ENDPOINTS          AGE
app                      10.0.0.1:8080   173m
```

when pod is `not ready`
```bash
$ kubectl get endpoints
NAME                  ENDPOINTS          AGE
app                                                     168m
```

when pod is `downscaled`
```bash
$ kubectl get endpoints
NAME                  ENDPOINTS          AGE
app                      <none>                  169m   
```

When the pod is not ready the endpoint has a list of ` notReadyAddresses`
```
subsets:
- notReadyAddresses:
  - ip: 10.0.0.1
  ```

Maybe you could check the state of the endpoint and do a failover?

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a deployement with a readiness probe
2. Export the service
3. Make sure one of the deployments is not ready
4. Try to resolve the service on the clusterset.local domain it fails or timesout.

**Comment by dfarrell07** [comment]
Thanks for the report @MartijnStraatman! Discussing with @aswinsuryan, @vthapar, and @tpantelis, it seems like we need to adjust our handling of notReadyAddresses to avoid this.

It would help to know if this is headless or clusterIP service.

**Comment by MartijnStraatman** [comment]
This was a clusterIP service. I have not tested headless services yet.
