### ISSUE TITLE
Add round robin selection to IPs returned by lighthouse plugin

### ISSUE THREAD

**Issue by vthapar** [submariner-io/lighthouse#114]
Modify lighthouse plugin to use round robin selection from list of IPs for a given multi cluster service.

**Comment by danibachar** [comment]
On it 👍

**Comment by nyechiel** [comment]
@manosnoam @pinikomarov code is node, ready for testing

**Comment by manosnoam** [comment]
@vthapar  Can you tell me how to reproduce ?

@nyechiel I think we should add this test to E2E.

**Comment by danibachar** [comment]
@manosnoam see - [this issue](https://github.com/submariner-io/lighthouse/issues/235)

**Comment by manosnoam** [comment]
Opened test request:
https://github.com/submariner-io/lighthouse/issues/340
