### ISSUE TITLE
Add support for headless services

### ISSUE THREAD

**Issue by nyechiel** [submariner-io/lighthouse#117]
With "headless" service, instead of a single Service IP with load-balancing, the platform should return the IPs of associated Pods. This allows to interact directly with the Pods instead of a proxy. 

An headless services can be configured by explicitly specifying "None" for the clusterIP (.spec.clusterIP), and can be utilized with or without selectors: https://kubernetes.io/docs/concepts/services-networking/service/#headless-services

**Comment by nyechiel** [comment]
This was requested by @hyunsun. 

/CC @vthapar

**Comment by aswinsuryan** [comment]
Some initial thoughts about the requirements

- The  query with search path <pod-name>.<svcname>.<ns>.svc.supercluster.local should just return the pods IP with that name. (This query may not succeed if the pods are part of a deployment)
- The pod name here corresponds to the pod name in the metadata of the k8s pod resource.
- The pod names will not be unique across clusters. This needs to be made predictable
    - Can append cluster name to podname
    - Can use a different search path for each clusters
- The query with the search path <svcname>.<ns>.svc.supercluster.cluster.local should return a list of A records with pod Ips from all the clusters.
- The clients can be easily configured to use svc.supercluster.cluster.local
- The use-case can be tested with any headless service backed by a stateful set.
