### ISSUE TITLE
PANICKED: while running LH e2e tests on OCP 4.12.10

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/lighthouse#1184]
**What happened**:
While running the `subctl verify --only service-discovery ...` tests on an OCP 4.12.10 cluster on Azure, the following was seen in the output.

![Screenshot from 2023-04-05 13-27-10](https://user-images.githubusercontent.com/6574656/230018024-752b76ea-273b-4da4-a132-1c7498024a52.png)

The final test-result shows that its all success, but in the last test, we could see the following

```
[PANICKED] in [AfterEach] - runtime/panic.go:113 @ 04/05/23 13:22:42.014
...
 There were additional failures detected.  To view them in detail run ginkgo -vv
```

**What you expected to happen**:

I'm not sure if this is really pointing to some issue or not, but it might be good to take a close look to understand why the PANICKED log is seen.

**How to reproduce it (as minimally and precisely as possible)**:
Seen with OCP 4.12.10 on Azure clusters and subctl 0.15.0-rc0 image.

**Comment by sridhargaddam** [comment]
Full logs: 
[verify-output.txt](https://github.com/submariner-io/lighthouse/files/11157228/verify-output.txt)

**Comment by skitt** [comment]
In UX terms this is similar to https://github.com/submariner-io/subctl/issues/47 (but this is probably a different underlying problem). In any case `AfterEach` mustn’t panic, but the logs don’t point to the actual panic.

**Comment by vthapar** [comment]
> In UX terms this is similar to [submariner-io/subctl#47](https://github.com/submariner-io/subctl/issues/47) (but this is probably a different underlying problem). In any case `AfterEach` mustn’t panic, but the logs don’t point to the actual panic.

Also, it is showing up in a test that is actually skipped. Panic is likely somewhere else but log is not showing correct location.

@sridhargaddam Would it be possible to run e2e manuall from lighthouse repository with `ginkgo -vv` flag?

**Comment by sridhargaddam** [comment]
> @sridhargaddam Would it be possible to run e2e manuall from lighthouse repository with `ginkgo -vv` flag?

I had to destroy the setup for a different configuration, so I do not have access to it anymore.

**Comment by tpantelis** [comment]
The panic actually occurs every time but is only logged if `--verbose` is enabled. I [reproduced it in CI](https://github.com/tpantelis/subctl/actions/runs/4618356119/jobs/8165706896?pr=6#step:3:2120) by setting the `verbose`  flag to `true`. It doesn't fail the test nor log the stack trace b/c the test is skipped. The panic occurs in [SetHealthCheckIP](https://github.com/submariner-io/lighthouse/blob/01d9f9ffd8ddc622faba611091a55074292d590f/test/e2e/discovery/service_discovery.go#L112) in `AfterEach` b/c `framework.ClusterC` isn't defined. We just need to skip the call to `SetHealthCheckIP` if the test is skipped.
