### ISSUE TITLE
GlobalIP not assigned in pod "init" phase

### ISSUE THREAD

**Issue by davtex** [submariner-io/lighthouse#1342]
**What happened**:
I am experimenting with Submariner with Globalnet and Apache Cassandra -> NoSQL database that is not exactly cloud-friendly and relies heavily on P2P connections. For it to work correctly in multi-cluster environment, a parameter "broadcast_address" needs to be configured before startup -> Cassandra uses this value to "announce" on which IP it is available to the rest of the cluster. In non-Submariner setups this would be some sort of node/loadbalancer publicIP, in case of Submariner+Globalnet this would be GlobalIP. So theoretically I just need to configure GlobalIP in Cassandra config file before pod is started and I should be done.

Obvious choice for me here is to use initContainer to query endpointslices from kube-apiserver and add returned GlobalIP to Cassandra config. But here comes the issue -> even though pod already has PodIP assigned, Submariner waits for pod to be in "Running" phase to assign GlobalIP, meaning I am unable to query it since initContainers run during pod's "Init" phase -> before Running phase. FYI I am using "publishNotReadyAddresses: true" and service is headless -> lighthouse complains that GlobalIP has not yet been assigned.

**What you expected to happen**:
I expect GlobalIP to be assigned as soon as PodIP is available so it can be used for various tasks in initContainers.

**How to reproduce it (as minimally and precisely as possible)**:
Create simple deployment with headless service and add initContainer -> GlobalIP won't be assigned until pod enters Running phase

**Environment**:
- OCP: 4.13.0-0.okd-2023-05-22-052007
- Submariner 0.15.2
- Cloud provider or hardware configuration: 2x vSphere clusters on-premise

**Comment by sridhargaddam** [comment]
CC: @tpantelis @vthapar

**Comment by tpantelis** [comment]
I think that's this b/c of [this code and TODO](https://github.com/submariner-io/submariner/blob/bf8acf121f20558c93cfc291030036c38e5d5e69/pkg/globalnet/controllers/ingress_pod_controller.go#L122) in globalnet. We should honor the _publishNotReadyAddresses_ annotation.
