### ISSUE TITLE
ServiceImport does not contain ClusterSetIPs

### ISSUE THREAD

**Issue by tanujd11** [submariner-io/lighthouse#1349]
**What happened**:
I am testing submariner on kind setup. I have created a service of type clusterIP and have exported the service to the ClusterSet. I am able to see in the logs of the lighthouse agent that serviceImportSpec returned is:

```
Returning ServiceImport default/backend: spec: {
  "ports": [
    {
      "name": "http",
      "protocol": "TCP",
      "port": 3000
    }
  ],
  "ips": [
    "242.1.255.253"
  ],
  "type": "ClusterSetIP",
  "sessionAffinityConfig": {}
}

```

But the actual serviceImport object does not contain the IPs. Following is the resultant ServiceImport:

```
k get serviceImports backend -o yaml
apiVersion: multicluster.x-k8s.io/v1alpha1
kind: ServiceImport
metadata:
  creationTimestamp: "2023-08-30T08:03:10Z"
  generation: 2
  name: backend
  namespace: default
  resourceVersion: "11596"
  uid: ac30d329-1f10-4115-b430-ee43f7deaf6d
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
  type: ClusterSetIP
status:
  clusters:
  - cluster: cluster2
```

Note that the traffic itself is working:
```
curl --head  nginx.default.svc.clusterset.local 
HTTP/1.1 200 OK
Server: nginx/1.25.2
Date: Wed, 30 Aug 2023 09:20:49 GMT
Content-Type: text/html
Content-Length: 615
Last-Modified: Tue, 15 Aug 2023 17:03:04 GMT
Connection: keep-alive
ETag: "64dbafc8-267"
Accept-Ranges: bytes
```

**What you expected to happen**:

Expectation is I see the IPs in ServiceImport generated.

**How to reproduce it (as minimally and precisely as possible)**:
```
git clone https://github.com/submariner-io/submariner-operator
make clusters
# Run below for cluster1
subctl deploy-broker --kubeconfig output/kubeconfigs/kind-config-cluster1 --globalnet
subctl join --kubeconfig output/kubeconfigs/kind-config-cluster1 broker-info.subm --clusterid cluster1 --natt=false
# Run below for cluster2
subctl join --kubeconfig output/kubeconfigs/kind-config-cluster2 broker-info.subm --clusterid cluster2 --natt=false

# Run the nginx application with ClusterIP svc and export it to clusterSet:
kubectl --kubeconfig output/kubeconfigs/kind-config-cluster2 create deployment nginx --image=nginx
kubectl --kubeconfig output/kubeconfigs/kind-config-cluster2 expose deployment nginx --port=80
subctl export service --kubeconfig output/kubeconfigs/kind-config-cluster2 --namespace default nginx
```

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by vthapar** [comment]
The spec you see in log is that cluster's ServiceImport. The generated ServiceImport is the aggregate of such ServiceImports from all clusters that have exported the service. The IPs are now available in EndpointSlices for the service, not ServiceImport. In future the CLusterSetIP will be used for the VirtualIP of the exported service, as per the MCS API spec.

This change was done as part of https://github.com/submariner-io/lighthouse/pull/1144

**Comment by tanujd11** [comment]
@vthapar Closing the issue. Have created https://github.com/submariner-io/lighthouse/issues/1350 for implementing the VirtualIP mentioned by you. Thanks
