### ISSUE TITLE
lighthouse-coredns cannot resolve  .clusterset.local names

### ISSUE THREAD

**Issue by jinglina** [submariner-io/lighthouse#1357]
using command ```subctl export service xxx -n ns1``` to create an exported service. It can be solved in local cluster using **xxx.ns1.svc.clusterset.local** or globalip. But It cannot be resolved in other join clusters using domain name.
I have checked lighthouse-coredns logs, it shows NOERROR rcode when curing it, but it can be solved using ips.

I cannot figure out why, any suggestions?

**Comment by jinglina** [comment]
in my k8s cluster, calico cni is choosen and ippool is created and when ```sbuctl show connections``` , it shows conencted.

**Comment by jinglina** [comment]
lighthouse-coredns logs:
2023/08/31 19:08:03 [INFO] plugin/lighthouse: Initializing dns query counter
W0831 19:08:03.596871       1 client_config.go:618] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
[INFO] plugin/lighthouse: submariner-lighthouse-coredns version: release-0.15-a63289692af9
[INFO] plugin/lighthouse(Gateway): Setting localClusterID from env: "numa"
[INFO] plugin/lighthouse(Gateway): Starting Gateway status Controller
[INFO] plugin/lighthouse(Resolver): Starting Resolver Controller
[INFO] plugin/lighthouse(Gateway): Updating the gateway status map[string]bool{"mesh":true, "numa":true, "test1":true} 
clusterset.local.:53
CoreDNS-1.10.1
linux/amd64, go1.19.9, 
[INFO] plugin/lighthouse(Resolver): Put ServiceImport "hjw-nssub1/dp-hjw-sub1-tom1-ngxv"
[INFO] 10.237.106.210:40395 - 18850 "A IN dp-hjw-sub1-tom1-ngxv.hjw-nssub1.svc.clusterset.local. udp 71 false 512" NOERROR qr,aa,rd 71 0.000139218s
[INFO] 10.238.28.185:53848 - 56690 "A IN dp-hjw-sub1-tom1-ngxv.hjw-nssub1.svc.clusterset.local. udp 71 false 512" NOERROR qr,aa,rd 71 0.000156044s

**Comment by jinglina** [comment]
[root@node3 ~]# subctl show all
Cluster "cluster.local"
 ✓ Detecting broker(s)
 ✓ No brokers found

 ✓ Showing Connections
GATEWAY   CLUSTER   REMOTE IP      NAT   CABLE DRIVER   SUBNETS        STATUS      RTT avg.
node2     test1     100.2.216.42   no    libreswan      242.4.0.0/16   connected   554.398µs
node1     mesh      100.2.220.14   no    libreswan      242.3.0.0/16   connected   511.113µs

 ✓ Showing Endpoints
CLUSTER   ENDPOINT IP    PUBLIC IP      CABLE DRIVER   TYPE
numa      100.2.220.13   100.2.220.13   libreswan      local
test1     100.2.216.42   100.2.216.42   libreswan      remote
mesh      100.2.220.14   100.2.220.14   libreswan      remote

 ✓ Showing Gateways
NODE    HA STATUS   SUMMARY
node1   active      All connections (2) are established

 ✓ Showing Network details
    Discovered network details via Submariner:
        Network plugin:  calico
        Service CIDRs:   [10.232.0.0/14]
        Cluster CIDRs:   [10.236.0.0/14]
        Global CIDR:     242.2.0.0/16

 ✓ Showing versions
COMPONENT                       REPOSITORY               VERSION
submariner-gateway              100.2.96.162:8089/icks   0.15.2
submariner-routeagent           100.2.96.162:8089/icks   0.15.2
submariner-globalnet            100.2.96.162:8089/icks   0.15.2
submariner-metrics-proxy        100.2.96.162:8089/icks   0.15.2
submariner-operator             100.2.96.162:8089/icks   0.15.2
submariner-lighthouse-agent     100.2.96.162:8089/icks   0.15.2
submariner-lighthouse-coredns   100.2.96.162:8089/icks   0.15.2

**Comment by jinglina** [comment]
Since  using globalip can get right response, I think it is a pure coredns problems, right?

**Comment by jinglina** [comment]
I  have found the problems. K8s version in  borker cluster is 1.20, it cannot support endpointslice apiVersion: discovery.k8s.io/v1beta1， so endpointslice cannot be created in broker cluster
In fact , in submariner.io readme，Minimum supported Kubernetes version is **1.17**, which we should pay attention.

**Comment by skitt** [comment]
Thanks for the investigation @jinglina, the documentation needs to be made clearer — Lighthouse needs Kubernetes 1.22 or later (only the connectivity part of Submariner is tested on 1.19 and later).

Please don’t ping individual users; two of the users you notified are no longer involved with the project.

**Comment by skitt** [comment]
https://github.com/submariner-io/subctl/pull/897 enforces version 1.21 if service discovery is enabled.

**Comment by skitt** [comment]
https://github.com/submariner-io/submariner-website/pull/1007 updates the web site.

**Comment by jinglina** [comment]
> Thanks for the investigation @jinglina, the documentation needs to be made clearer — Lighthouse needs Kubernetes 1.22 or later (only the connectivity part of Submariner is tested on 1.19 and later).
> 
> Please don’t ping individual users; two of the users you notified are no longer involved with the project.

Sorry for that.

**Comment by jinglina** [comment]
In fact, the broker cluster (just usign as broker ) needs k8s version that support **discovery.k8s.io/v1** (>=1.21) , or it won't create endpointslice resource  successfully. As a result, the domain name won't be solved.

Will we paln to support the converter from v1 to v1beta1?

**Comment by jinglina** [comment]
And another question, lighthouse-coredns cannot find related DNS record in other clusters, why the rcode is NOERROR, it is quite  confusing.
