### ISSUE TITLE
Missing metric: submariner_service_export

### ISSUE THREAD

**Issue by maayanf24** [submariner-io/lighthouse#1363]
**What happened**:
The metric `submariner_service_Export` is not exposed, using 0.16.0-rc0

**What you expected to happen**:
To see the metric `submariner_service_Export`

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by tpantelis** [comment]
The `submariner_service_export` metric got lost in  the shuffle during during the refactoring in the last couple releases.
