### ISSUE TITLE
TestDay: OCP 4.13 on AWS E2E fails [Test Headless Service Discovery Across Clusters]

### ISSUE THREAD

**Issue by vthapar** [submariner-io/lighthouse#1389]
**What happened**:
`subctl verify` failed with following error:

• [FAILED] [417.854 seconds]
[discovery] Test Headless Service Discovery Across Clusters when a pod tries to resolve a headless service which is exported locally and in a remote cluster [It] should resolve the backing pod IPs from both clusters
github.com/submariner-io/lighthouse@v0.16.0-rc1/test/e2e/discovery/headless_services.go:48

  Timeline >>
  STEP: Creating namespace objects with basename "discovery" @ 09/27/23 18:32:47.551
  STEP: Generated namespace "e2e-tests-discovery-tt4jf" in cluster "vthapar-acmhub" to execute the tests in @ 09/27/23 18:32:47.8
  STEP: Creating namespace "e2e-tests-discovery-tt4jf" in cluster "vthapar-red" @ 09/27/23 18:32:47.8
  STEP: Creating an Nginx Deployment on "vthapar-red" @ 09/27/23 18:32:48.056
  STEP: Creating a Nginx Headless Service on "vthapar-red" @ 09/27/23 18:32:54.075
  STEP: Creating serviceExport nginx-headless.e2e-tests-discovery-tt4jf on "vthapar-red" @ 09/27/23 18:32:54.329
  STEP: Retrieving ServiceExport nginx-headless.e2e-tests-discovery-tt4jf on "vthapar-red" @ 09/27/23 18:32:54.583
  STEP: Retrieving ServiceImport for "nginx-headless" in ns "e2e-tests-discovery-tt4jf" on "vthapar-acmhub" @ 09/27/23 18:33:00.345
  STEP: Creating an Nginx Deployment on "vthapar-acmhub" @ 09/27/23 18:33:00.593
  STEP: Creating a Nginx Headless Service on "vthapar-acmhub" @ 09/27/23 18:33:06.589
  STEP: Creating serviceExport nginx-headless.e2e-tests-discovery-tt4jf on "vthapar-acmhub" @ 09/27/23 18:33:06.848
  STEP: Retrieving ServiceExport nginx-headless.e2e-tests-discovery-tt4jf on "vthapar-acmhub" @ 09/27/23 18:33:07.097
  STEP: Retrieving ServiceImport for "nginx-headless" in ns "e2e-tests-discovery-tt4jf" on "vthapar-acmhub" @ 09/27/23 18:33:12.846
  STEP: Creating a Netshoot Deployment on "vthapar-acmhub" @ 09/27/23 18:33:13.096
  STEP: Retrieving Endpoints for nginx-headless on "vthapar-red" @ 09/27/23 18:33:19.09
  STEP: Retrieving Endpoints for nginx-headless on "vthapar-acmhub" @ 09/27/23 18:33:19.342
  STEP: Executing "dig +short nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local" to verify IPs [10.132.2.24 10.128.2.44] for service "nginx-headless" "are" discoverable @ 09/27/23 18:33:19.59
  Sep 27 18:33:19.590: INFO: ExecWithOptions &{Command:[dig +short nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local] Namespace:e2e-tests-discovery-tt4jf PodName:netshootqvwxz-6c64666d54-s9r42 ContainerName:netshoot Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:false}
  STEP: Validating that dig result are "10.132.2.24\n10.132.2.24\n10.128.2.44\n10.128.2.44" @ 09/27/23 18:33:21.204
  STEP: Executing "dig +short SRV http.tcp.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local" to verify hostNames [nginx-demo-7d85c49756-plvgz] for service "nginx-headless" "are" discoverable @ 09/27/23 18:33:21.204
  Sep 27 18:33:21.204: INFO: ExecWithOptions &{Command:[dig +short SRV http.tcp.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local] Namespace:e2e-tests-discovery-tt4jf PodName:netshootqvwxz-6c64666d54-s9r42 ContainerName:netshoot Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:false}
  STEP: Validating that dig result are "" @ 09/27/23 18:33:27.807
  Sep 27 18:33:27.807: INFO: expected execution result "" to contain "nginx-demo-7d85c49756-plvgz.vthapar-red.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local" and 80
  Sep 27 18:33:27.807: INFO: ExecWithOptions &{Command:[dig +short SRV http.tcp.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local] Namespace:e2e-tests-discovery-tt4jf PodName:netshootqvwxz-6c64666d54-s9r42 ContainerName:netshoot Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:false}
  STEP: Validating that dig result are "" @ 09/27/23 18:33:34.407
  Sep 27 18:33:34.407: INFO: expected execution result "" to contain "nginx-demo-7d85c49756-plvgz.vthapar-red.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local" and 80
  Sep 27 18:33:39.407: INFO: ExecWithOptions &{Command:[dig +short SRV http.tcp.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local] Namespace:e2e-tests-discovery-tt4jf PodName:netshootqvwxz-6c64666d54-s9r42 ContainerName:netshoot Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:false}
  STEP: Validating that dig result are "" @ 09/27/23 18:33:45.989
  Sep 27 18:33:45.989: INFO: expected execution result "" to contain "nginx-demo-7d85c49756-plvgz.vthapar-red.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local" and 80
  Sep 27 18:33:45.989: INFO: ExecWithOptions &{Command:[dig +short SRV http.tcp.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local] Namespace:e2e-tests-discovery-tt4jf PodName:netshootqvwxz-6c64666d54-s9r42 ContainerName:netshoot Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:false}
  STEP: Validating that dig result are "" @ 09/27/23 18:33:52.591
  Sep 27 18:33:52.591: INFO: expected execution result "" to contain "nginx-demo-7d85c49756-plvgz.vthapar-red.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local" and 80
  Sep 27 18:33:52.591: INFO: ExecWithOptions &{Command:[dig +short SRV http.tcp.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local] Namespace:e2e-tests-discovery-tt4jf PodName:netshootqvwxz-6c64666d54-s9r42 ContainerName:netshoot Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:false}
  STEP: Validating that dig result are "" @ 09/27/23 18:33:59.168
  Sep 27 18:33:59.168: INFO: expected execution result "" to contain "nginx-demo-7d85c49756-plvgz.vthapar-red.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local" and 80
  Sep 27 18:33:59.168: INFO: ExecWithOptions &{Command:[dig +short SRV http.tcp.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local] Namespace:e2e-tests-discovery-tt4jf PodName:netshootqvwxz-6c64666d54-s9r42 ContainerName:netshoot Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:false}
  STEP: Validating that dig result are "" @ 09/27/23 18:34:05.749
  Sep 27 18:34:05.749: INFO: expected execution result "" to contain "nginx-demo-7d85c49756-plvgz.vthapar-red.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local" and 80
  Sep 27 18:34:05.749: INFO: ExecWithOptions &{Command:[dig +short SRV http.tcp.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local] Namespace:e2e-tests-discovery-tt4jf PodName:netshootqvwxz-6c64666d54-s9r42 ContainerName:netshoot Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:false}
  STEP: Validating that dig result are "" @ 09/27/23 18:34:12.416
  Sep 27 18:34:12.416: INFO: expected execution result "" to contain "nginx-demo-7d85c49756-plvgz.vthapar-red.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local" and 80
  Sep 27 18:34:12.416: INFO: ExecWithOptions &{Command:[dig +short SRV http.tcp.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local] Namespace:e2e-tests-discovery-tt4jf PodName:netshootqvwxz-6c64666d54-s9r42 ContainerName:netshoot Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:false}
  STEP: Validating that dig result are "" @ 09/27/23 18:34:19.692
  Sep 27 18:34:19.692: INFO: expected execution result "" to contain "nginx-demo-7d85c49756-plvgz.vthapar-red.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local" and 80
  Sep 27 18:34:19.692: INFO: ExecWithOptions &{Command:[dig +short SRV http.tcp.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local] Namespace:e2e-tests-discovery-tt4jf PodName:netshootqvwxz-6c64666d54-s9r42 ContainerName:netshoot Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:false}
  STEP: Validating that dig result are "" @ 09/27/23 18:34:30.107
  Sep 27 18:34:30.107: INFO: expected execution result "" to contain "nginx-demo-7d85c49756-plvgz.vthapar-red.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local" and 80
  Sep 27 18:34:30.107: INFO: ExecWithOptions &{Command:[dig +short SRV http.tcp.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local] Namespace:e2e-tests-discovery-tt4jf PodName:netshootqvwxz-6c64666d54-s9r42 ContainerName:netshoot Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:false}
  STEP: Validating that dig result are ";; communications error to 172.30.0.10#53: timed out" @ 09/27/23 18:34:47.46
  Sep 27 18:34:47.460: INFO: expected execution result ";; communications error to 172.30.0.10#53: timed out" to contain "nginx-demo-7d85c49756-plvgz.vthapar-red.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local" and 80
  Sep 27 18:34:47.460: INFO: ExecWithOptions &{Command:[dig +short SRV http.tcp.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local] Namespace:e2e-tests-discovery-tt4jf PodName:netshootqvwxz-6c64666d54-s9r42 ContainerName:netshoot Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:false}
  STEP: Validating that dig result are "" @ 09/27/23 18:34:55.326
  Sep 27 18:34:55.326: INFO: expected execution result "" to contain "nginx-demo-7d85c49756-plvgz.vthapar-red.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local" and 80
  Sep 27 18:34:55.326: INFO: ExecWithOptions &{Command:[dig +short SRV http.tcp.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local] Namespace:e2e-tests-discovery-tt4jf PodName:netshootqvwxz-6c64666d54-s9r42 ContainerName:netshoot Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:false}
  STEP: Validating that dig result are "" @ 09/27/23 18:35:04.671
  Sep 27 18:35:04.671: INFO: expected execution result "" to contain "nginx-demo-7d85c49756-plvgz.vthapar-red.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local" and 80
  Sep 27 18:35:04.671: INFO: ExecWithOptions &{Command:[dig +short SRV http.tcp.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local] Namespace:e2e-tests-discovery-tt4jf PodName:netshootqvwxz-6c64666d54-s9r42 ContainerName:netshoot Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:false}
  STEP: Validating that dig result are "" @ 09/27/23 18:35:15.947
  Sep 27 18:35:15.947: INFO: expected execution result "" to contain "nginx-demo-7d85c49756-plvgz.vthapar-red.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local" and 80
  Sep 27 18:35:15.947: INFO: ExecWithOptions &{Command:[dig +short SRV http.tcp.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local] Namespace:e2e-tests-discovery-tt4jf PodName:netshootqvwxz-6c64666d54-s9r42 ContainerName:netshoot Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:false}
  STEP: Validating that dig result are "" @ 09/27/23 18:35:26.604
  Sep 27 18:35:26.604: INFO: expected execution result "" to contain "nginx-demo-7d85c49756-plvgz.vthapar-red.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local" and 80
  Sep 27 18:35:26.604: INFO: ExecWithOptions &{Command:[dig +short SRV http.tcp.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local] Namespace:e2e-tests-discovery-tt4jf PodName:netshootqvwxz-6c64666d54-s9r42 ContainerName:netshoot Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:false}
  STEP: Validating that dig result are "" @ 09/27/23 18:35:36.755
  Sep 27 18:35:36.755: INFO: expected execution result "" to contain "nginx-demo-7d85c49756-plvgz.vthapar-red.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local" and 80
  Sep 27 18:35:36.755: INFO: ExecWithOptions &{Command:[dig +short SRV http.tcp.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local] Namespace:e2e-tests-discovery-tt4jf PodName:netshootqvwxz-6c64666d54-s9r42 ContainerName:netshoot Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:false}
  STEP: Validating that dig result are "" @ 09/27/23 18:35:46.391
  Sep 27 18:35:46.391: INFO: expected execution result "" to contain "nginx-demo-7d85c49756-plvgz.vthapar-red.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local" and 80
  Sep 27 18:35:46.391: INFO: ExecWithOptions &{Command:[dig +short SRV http.tcp.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local] Namespace:e2e-tests-discovery-tt4jf PodName:netshootqvwxz-6c64666d54-s9r42 ContainerName:netshoot Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:false}
  STEP: Validating that dig result are "" @ 09/27/23 18:35:57.934
  Sep 27 18:35:57.934: INFO: expected execution result "" to contain "nginx-demo-7d85c49756-plvgz.vthapar-red.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local" and 80
  Sep 27 18:35:57.934: INFO: ExecWithOptions &{Command:[dig +short SRV http.tcp.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local] Namespace:e2e-tests-discovery-tt4jf PodName:netshootqvwxz-6c64666d54-s9r42 ContainerName:netshoot Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:false}
  STEP: Validating that dig result are "" @ 09/27/23 18:36:09.014
  Sep 27 18:36:09.014: INFO: expected execution result "" to contain "nginx-demo-7d85c49756-plvgz.vthapar-red.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local" and 80
  Sep 27 18:36:09.014: INFO: ExecWithOptions &{Command:[dig +short SRV http.tcp.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local] Namespace:e2e-tests-discovery-tt4jf PodName:netshootqvwxz-6c64666d54-s9r42 ContainerName:netshoot Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:false}
  STEP: Validating that dig result are "" @ 09/27/23 18:36:19.401
  Sep 27 18:36:19.401: INFO: expected execution result "" to contain "nginx-demo-7d85c49756-plvgz.vthapar-red.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local" and 80
  Sep 27 18:36:19.401: INFO: ExecWithOptions &{Command:[dig +short SRV http.tcp.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local] Namespace:e2e-tests-discovery-tt4jf PodName:netshootqvwxz-6c64666d54-s9r42 ContainerName:netshoot Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:false}
  STEP: Validating that dig result are "" @ 09/27/23 18:36:29.295
  Sep 27 18:36:29.295: INFO: expected execution result "" to contain "nginx-demo-7d85c49756-plvgz.vthapar-red.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local" and 80
  Sep 27 18:36:29.295: INFO: ExecWithOptions &{Command:[dig +short SRV http.tcp.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local] Namespace:e2e-tests-discovery-tt4jf PodName:netshootqvwxz-6c64666d54-s9r42 ContainerName:netshoot Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:false}
  Sep 27 18:37:05.997: INFO: Retrying due to error  command terminated with exit code 9
  Sep 27 18:37:42.655: INFO: Retrying due to error  command terminated with exit code 9
  Sep 27 18:38:19.306: INFO: Retrying due to error  command terminated with exit code 9
  Sep 27 18:38:56.014: INFO: Retrying due to error  command terminated with exit code 9
  Sep 27 18:39:32.667: INFO: Retrying due to error  command terminated with exit code 9
  [FAILED] in [It] - github.com/submariner-io/shipyard@v0.16.0-rc1/test/e2e/framework/framework.go:562 @ 09/27/23 18:39:32.668
  STEP: Deleting namespace "e2e-tests-discovery-tt4jf" on cluster "vthapar-acmhub" @ 09/27/23 18:39:32.668
  STEP: Deleting namespace "e2e-tests-discovery-tt4jf" on cluster "vthapar-red" @ 09/27/23 18:39:33.505
  STEP: Retrieving EndpointSlices for "" in ns "e2e-tests-discovery-tt4jf" on "vthapar-red" @ 09/27/23 18:39:34.373
  STEP: Retrieving EndpointSlices for "" in ns "e2e-tests-discovery-tt4jf" on "vthapar-acmhub" @ 09/27/23 18:39:45.138
  << Timeline

  [FAILED] Failed to  service IP verification. expected execution result "" to contain "nginx-demo-7d85c49756-plvgz.vthapar-red.nginx-headless.e2e-tests-discovery-tt4jf.svc.clusterset.local" and 80
  Unexpected error:
      <exec.CodeExitError>: 
      command terminated with exit code 9
      {
          Err: <*errors.errorString | 0xc0008ca2f0>{
              s: "command terminated with exit code 9",
          },
          Code: 9,
      }
  occurred
  In [It] at: github.com/submariner-io/shipyard@v0.16.0-rc1/test/e2e/framework/framework.go:562 @ 09/27/23 18:39:32.668
------------------------------

**What you expected to happen**:
Test case should pass

**How to reproduce it (as minimally and precisely as possible)**:

Install submariner 0.16.0-rc1 on OCP 4.13 on AWS

**Anything else we need to know?**:

**Environment**:
OCP 4.13.3

submariner 0.16.0-rc1

NOTE: Error happens with verify when `--context` is set to same cluster as broker. If broker cluster is used as `--tocontext` it works fine.

**Comment by tpantelis** [comment]
This may be the same as https://github.com/submariner-io/lighthouse/issues/1341.

**Comment by vthapar** [comment]
> This may be the same as #1341.

I got error with 2 AWS clusters.

**Comment by dfarrell07** [comment]
We didn't see this in the latest test day. Closing for now, will re-open if we see it again.
