### ISSUE TITLE
add lighthouse e2e tests to downstream CI

### ISSUE THREAD

**Issue by pinikomarov** [submariner-io/lighthouse#211]
@Vishal Thapar @mkolesni @Tom Pantelis https://github.com/submariner-io/lighthouse/blob/9d0d2ef6768c78a844fc8933fa3d246a37705b81/test/e2e/discovery/service_discovery.go#L21 Hi , Do you guys know how/where these tests are run ? via github actions / subctl verify ? , thanks

test/e2e/discovery/service_discovery.go:21
var _ = Describe("[discovery] Test Service Discovery Across Clusters", func() {
<https://github.com/submariner-io/lighthouse|submariner-io/lighthouse>submariner-io/lighthouse | Added by GitHub

WIP: 

Vishal Thapar  11:45 AM
@pkomarov via both. Github Actions runs these in lighthouse CI e.g. https://github.com/submariner-io/lighthouse/actions/runs/170918828
Example of using subctl verify is in operator repo's CI e.g. https://github.com/submariner-io/submariner-operator/runs/876513305?check_suite_focus=true#step:5:8436

https://github.com/submariner-io/lighthouse/actions/runs/170918828

https://github.com/submariner-io/submariner-operator/runs/876513305?check_suite_focus=true#step:5:8436

**Comment by pinikomarov** [comment]
@manosnoam your dowsnstream CI is already running the lighthouse service discovery tests
: 
08:55:04 [discovery] Test Service Discovery Across Clusters when a pod tries to resolve a service in a remote cluster 
08:55:04   should be able to discover the remote service successfully
08:55:04   /go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/lighthouse/test/e2e/discovery/service_discovery.go:25
08:55:04 STEP: Creating namespace objects with basename "discovery"
[...]

this is because : 
discovery is already supplied to the subctl verify command: 
https://github.com/manosnoam/ocp-multi-cluster-tester/blob/fcc56a76e0949b3e050d053266ccd8c0b5b49704/setup_subm.sh#L2269

**Comment by pinikomarov** [comment]
so seeing that we have what we need , I'm closing this

**Comment by manosnoam** [comment]
@pinikomarov  thanks for looking into it.
The only drawback of it is that our junit report, which is generated by `go test` command (and not by `subctl verify`), will not include the results of servicediscovery.

I think we should still add service-discovery repo to our go test command.

**Comment by manosnoam** [comment]
@pinikomarov 
We're now running lighthouse ginkgo tests with ocp-multi-cluster-tester:

```
17:02:21  ### Testing Lighthouse End-to-End tests with GO ###
17:02:21  [/home/jenkins/workspace/debug_job]
17:02:21 
17:02:21 (conda-test) cd /home/jenkins/go/src/github.com/submariner-io/lighthouse
17:02:21 
17:02:21 [./setup_subm.sh] [lighthouse]
17:02:21 
17:02:22 (conda-test) export KUBECONFIG="/mnt/skynet-data/pkomarov-env/pkomarov-cluster-a/auth/kubeconfig:/mnt/skynet-data/pkomarov-env/ocpup/.config/cl2/auth/kubeconfig"
17:02:22 (conda-test) /mnt/skynet-data/pkomarov-env/GOBIN/oc config get-contexts
17:02:22 CURRENT   NAME                 CLUSTER              AUTHINFO   NAMESPACE
17:02:22 *         pkomarov-cluster-a   pkomarov-cluster-a   admin      test-submariner
17:02:22           pkomarov-cluster-b   default-cl2          admin      test-submariner
17:02:22 (conda-test) export GO111MODULE="on"
17:02:22 (conda-test) go env
17:02:22 GO111MODULE="on"
17:02:22 GOARCH="amd64"
17:02:22 GOBIN="/mnt/skynet-data/pkomarov-env/miniconda/envs/conda-test/go/bin"
17:02:22 GOCACHE="/home/jenkins/.cache/go-build"
17:02:22 GOENV="/home/jenkins/.config/go/env"
17:02:22 GOEXE=""
17:02:22 GOFLAGS=""
17:02:22 GOHOSTARCH="amd64"
17:02:22 GOHOSTOS="linux"
17:02:22 GONOPROXY=""
17:02:22 GONOSUMDB=""
17:02:22 GOOS="linux"
17:02:22 GOPATH="/home/jenkins/go"
17:02:22 GOPRIVATE=""
17:02:22 GOPROXY="https://proxy.golang.org,direct"
17:02:22 GOROOT="/mnt/skynet-data/pkomarov-env/miniconda/envs/conda-test/go"
17:02:22 GOSUMDB="sum.golang.org"
17:02:22 GOTMPDIR=""
17:02:22 GOTOOLDIR="/mnt/skynet-data/pkomarov-env/miniconda/envs/conda-test/go/pkg/tool/linux_amd64"
17:02:22 GCCGO="gccgo"
17:02:22 AR="ar"
17:02:22 CC="/dev/null"
17:02:22 CXX="/dev/null"
17:02:22 CGO_ENABLED="0"
17:02:22 GOMOD="/home/jenkins/go/src/github.com/submariner-io/lighthouse/go.mod"
17:02:22 CGO_CFLAGS="-g -O2"
17:02:22 CGO_CPPFLAGS=""
17:02:22 CGO_CXXFLAGS="-g -O2"
17:02:22 CGO_FFLAGS="-g -O2"
17:02:22 CGO_LDFLAGS="-g -O2"
17:02:22 PKG_CONFIG="pkg-config"
17:02:22 GOGCCFLAGS="-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build467706121=/tmp/go-build -gno-record-gcc-switches"
17:02:22 (conda-test) go test -v ./test/e2e -timeout 30m -ginkgo.v -ginkgo.trace -ginkgo.randomizeAllSpecs -ginkgo.noColor -ginkgo.reportPassed -ginkgo.reportFile "/home/jenkins/workspace/debug_job/lighthouse_e2e_junit.xml" -args --dp-context pkomarov-cluster-a --dp-context pkomarov-cluster-b --submariner-namespace submariner-operator --connection-timeout 30 --connection-attempts 3
17:02:27 go: finding github.com/imdario/mergo v0.3.8
17:02:27 go: finding cloud.google.com/go v0.41.0
17:05:56 === RUN   TestE2E
17:05:56 Running Suite: Submariner E2E suite
17:05:56 ===================================
17:05:56 Random Seed: 1602597956 - Will randomize all specs
17:05:56 Will run 11 of 11 specs
```
