### ISSUE TITLE
Add support for StatefulSets

### ISSUE THREAD

**Issue by vthapar** [submariner-io/lighthouse#215]
To support StatefulSets [https://kubernetes.io/docs/concepts/workloads/controllers/statefulset] we need to provide means to access individual pods in the set using hostnames, rather than just return list of PodIPs as we do in Headless Services. This is currently not possible with what we have in ServiceImports and will likely need EndpointSlice support.

**Comment by sridhargaddam** [comment]
@vthapar If this issue targets only non-globalnet use-cases, can you please open a new issue for Globalnet use-case so that we don't miss it. Thanks.

**Comment by manosnoam** [comment]
I'm closing this and open a new E2E test request
