### ISSUE TITLE
Deprecate and cleanup multiclusterservices CRD

### ISSUE THREAD

**Issue by vthapar** [submariner-io/lighthouse#216]
We no longer use multiclusterservices, already replaced with ServiceImports. Deprecate the spec and cleanup any references and usages of it in code, scripts and deployments.

**Comment by tpantelis** [comment]
bump

**Comment by nyechiel** [comment]
@vthapar @aswinsuryan  is this something you are looking at?

**Comment by nyechiel** [comment]
Done for Lighthouse, need to ensure that the Operator does not install the old CRDs.

**Comment by nyechiel** [comment]
@vthapar @skitt is this being worked on?

**Comment by skitt** [comment]
Yes, I’m working on it.
