### ISSUE TITLE
Ligththouse should not return service-ip from a cluster which does not have  healthy backend pods.

### ISSUE THREAD

**Issue by aswinsuryan** [submariner-io/lighthouse#234]
Lighthouse should remove the cluster-ip from the ServiceImport , if that cluster does not have any active backend pods. for the service.

**Comment by vthapar** [comment]
Fixed by #242

**Comment by mangelajo** [comment]
Fixed by #242

**Comment by mangelajo** [comment]
It was open for QE, I guess it makes sense to assign to @manosnoam when fixed an QE flag is set.

**Comment by manosnoam** [comment]
@aswinsuryan Can you provide reproduction steps for this scenario to verify ?

**Comment by aswinsuryan** [comment]
> @aswinsuryan Can you provide reproduction steps for this scenario to verify ?

A service shall be deployed in two clusters and reduce the replicas in one of the service  to zero and check if the clusterIP is that of the other one which has active backend pods and if the service can be accessed using it.

**Comment by manosnoam** [comment]
@aswinsuryan  Can you tell me how to reproduce ?

@nyechiel I think we should add this test to E2E.

**Comment by aswinsuryan** [comment]
> @aswinsuryan , @nyechiel I think we should add this test to E2E.

Do these steps mentioned in above comment [1] work for you?

[1] https://github.com/submariner-io/lighthouse/issues/234#issuecomment-683677761

**Comment by vthapar** [comment]
> @aswinsuryan , @nyechiel I think we should add this test to E2E.

It is already part of E2E. If replicaset is 0, we don't return IP of that service.
