### ISSUE TITLE
When a service is available in multiple clusters, DNS apparently only returns one

### ISSUE THREAD

**Issue by skitt** [submariner-io/lighthouse#235]
In a setup with two clusters, both exporting the same service, the imports are synchronised:

```
NAMESPACE               NAME                                              AGE
submariner-k8s-broker   nginx-default-gn2                                 4d16h
submariner-k8s-broker   submariner-test-app-quattro-submariner-test-gn2   15m
submariner-k8s-broker   submariner-test-app-quattro-submariner-test-gn3   35m
submariner-operator     nginx-default-gn2                                 4d16h
submariner-operator     submariner-test-app-quattro-submariner-test-gn2   15m
submariner-operator     submariner-test-app-quattro-submariner-test-gn3   35m
```

(on the broker cluster) but `dig` only ever returns one of the IP addresses — the first one to be exported in this case.

**Comment by sridhargaddam** [comment]
@skitt @mangelajo @nyechiel This should be fixed via the following right - https://github.com/submariner-io/lighthouse/issues/114

**Comment by skitt** [comment]
> @skitt @mangelajo @nyechiel This should be fixed via the following right - #114

Yes, it should!

**Comment by nyechiel** [comment]
https://github.com/submariner-io/lighthouse/issues/114 is merged, ready for testing

**Comment by manosnoam** [comment]
@skitt  Can you tell me how to reproduce ?

@tpantelis maybe we should add this test to E2E ?

**Comment by danibachar** [comment]
@manosnoam Just to clarify - Each DNS query (i.e dig) should return a different IP (i.e each time a different clusterIP).
BTW - @skitt @vthapar - How is the cache working here? Does CoreDNS offer a cache for DNS queries? Is it possible that the CoreDNS will use some caching, will not pass the request to Lighthouse as it found an older response, and will return the same IP as the last request?

**Comment by manosnoam** [comment]
Opened test request:
https://github.com/submariner-io/lighthouse/issues/340
