### ISSUE TITLE
DNS resolution is very erratic sometimes

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/lighthouse#236]
**Deploy three KIND clusters (you can use submariner repo and execute "make clusters")**
1. subctl deploy-broker --kubeconfig output/kubeconfigs/kind-config-cluster1 --service-discovery
2. subctl join --kubeconfig output/kubeconfigs/kind-config-cluster2 --clusterid cluster2 --disable-nat --version devel ./broker-info.subm --cable-driver libreswan
3. subctl join --kubeconfig output/kubeconfigs/kind-config-cluster3 --clusterid cluster3 --disable-nat --version devel ./broker-info.subm --cable-driver libreswan
Note: Used latest subctl

[sgaddam@localhost submariner]$ export KUBECONFIG=output/kubeconfigs/kind-config-cluster2
[sgaddam@localhost submariner]$ kubectl get svc -n submariner-operator
NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE
submariner-lighthouse-coredns ClusterIP **100.92.253.164** 53/UDP 42m
submariner-operator-metrics ClusterIP 100.92.66.37 8383/TCP,8686/TCP 42m
[sgaddam@localhost submariner]$

ConfigMap of CoreDNS
apiVersion: v1
data:
Corefile: |
#lighthouse
supercluster.local:53 {
forward . **100.92.253.164** <--- This matches with the serviceip of lighthouse-coredns
}
.:53 {
errors
health {
lameduck 5s
}
ready
kubernetes cluster2.local in-addr.arpa ip6.arpa {
pods insecure
fallthrough in-addr.arpa ip6.arpa
ttl 30
}
prometheus :9153
forward . /etc/resolv.conf
cache 30
loop
reload
loadbalance
}

After removing the submariner.io/gateway label on active gatewaynode of cluster2, enginePod is terminated, and when we try DNS resolution from the Pod, it's very erratic (PSB).

**In clientPod (deployed via kubectl run netshoot-2-1 -i --tty --image nicolaka/netshoot -- /bin/bash) on cluster-2**
bash-5.0# The ping requests below were issued without any delay.
bash-5.0# ping nginx.default.svc.supercluster.local
PING nginx.default.svc.supercluster.local (100.93.129.152) 56(84) bytes of data.   **<--- Here ping resolves**
^C
--- nginx.default.svc.supercluster.local ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms

bash-5.0# 
bash-5.0# ping nginx.default.svc.supercluster.local                      
ping: nginx.default.svc.supercluster.local: Name does not resolve                 **<--- ping does not resolve**
bash-5.0#
bash-5.0# ping nginx.default.svc.supercluster.local
ping: nginx.default.svc.supercluster.local: Name does not resolve
bash-5.0#
bash-5.0# ping nginx.default.svc.supercluster.local
PING nginx.default.svc.supercluster.local (100.93.129.152) 56(84) bytes of data.  **<--- ping resolves again**
^C
--- nginx.default.svc.supercluster.local ping statistics ---
9 packets transmitted, 0 received, 100% packet loss, time 8215ms

After leaving the setup for some 20 mins, when I tried to run **ping/dig**, DNS does not resolve at all.

bash-5.0# ping nginx.default.svc.supercluster.local
ping: nginx.default.svc.supercluster.local: Name does not resolve
bash-5.0#

Re-verified the lighthouse-coredns serviceip and it matches with the ipaddress in configMap of CoreDNS, but still DNS does not work.

**Comment by sridhargaddam** [comment]
CC: @aswinsuryan @vthapar

**Comment by sridhargaddam** [comment]
**Behavior in a fresh setup (i.e., make clusters followed by the steps mentioned above)**

[sgaddam@localhost submariner]$ export KUBECONFIG=output/kubeconfigs/kind-config-cluster2
[sgaddam@localhost submariner]$ kubectl get svc -n submariner-operator
NAME                            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
**submariner-lighthouse-coredns   ClusterIP   100.92.253.164**   <none>        53/UDP              42m
submariner-operator-metrics     ClusterIP   100.92.66.37     <none>        8383/TCP,8686/TCP   42m
[sgaddam@localhost submariner]$ 

`ConfigMap of CoreDNS`
apiVersion: v1
data:
  Corefile: |
    #lighthouse
    supercluster.local:53 {
    **forward . 100.92.253.164       <--- This matches with the serviceip of lighthouse-coredns**
    }
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster2.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }

After removing the submariner.io/gateway label on active gatewaynode of cluster2, enginePod is terminated, and when we try DNS resolution from the Pod, it's very erratic (PSB).

**In clientPod on cluster-2**
bash-5.0# ping nginx.default.svc.supercluster.local
PING nginx.default.svc.supercluster.local (100.93.129.152) 56(84) bytes of data.
^C
--- nginx.default.svc.supercluster.local ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms

bash-5.0# 
bash-5.0# ping nginx.default.svc.supercluster.local
ping: nginx.default.svc.supercluster.local: Name does not resolve
bash-5.0# 
bash-5.0# ping nginx.default.svc.supercluster.local
ping: nginx.default.svc.supercluster.local: Name does not resolve
bash-5.0# 
bash-5.0# ping nginx.default.svc.supercluster.local
PING nginx.default.svc.supercluster.local (100.93.129.152) 56(84) bytes of data.
^C
--- nginx.default.svc.supercluster.local ping statistics ---
9 packets transmitted, 0 received, 100% packet loss, time 8215ms

After leaving the setup for some 20 mins, when I tried to run ping/dig, DNS does not resolve at all.

bash-5.0# ping nginx.default.svc.supercluster.local
ping: nginx.default.svc.supercluster.local: Name does not resolve
bash-5.0#

So, verified the lighthouse-coredns serviceip and it matches with the ipaddress in configMap of CoreDNS, but still DNS does not work.

**Comment by mangelajo** [comment]
@aswinsuryan @vthapar added you guys so you can track it, looks important, but of course, I suspect you won't have cycles right now.

**Comment by nyechiel** [comment]
@aswinsuryan @vthapar is there anything we need to do or further investigate here?

**Comment by aswinsuryan** [comment]
> @aswinsuryan @vthapar is there anything we need to do or further investigate here?

We need to verify the issue is still there as a lot changed in this  area. I will test it with the RC and update.

**Comment by nyechiel** [comment]
@aswinsuryan any update on this?

**Comment by aswinsuryan** [comment]
Verified the bug in  Submariner Project v0.8.0 in Kind and the issue was not seen. The DNS resolution was working fine even after waiting for 30 minutes after the shutdown of the gateway node.
