### ISSUE TITLE
Test Headless Service in Subctl 0.6.0

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/lighthouse#271]
This is to test Headless Service on Submariner 0.6.0, as documented in:
https://github.com/submariner-io/submariner-website/pull/251

_Originally posted by @aswinsuryan in https://github.com/submariner-io/lighthouse/issues/252#issuecomment-678137477_

**Comment by manosnoam** [comment]
Hi @nyechiel, @mangelajo, @tfreger, @pinikomarov 
A good way to make sure we're not missing testing of new features, is to remember that when creating a Doc issue about a new feature in Submariner (like this #251) - also add a new Test issue for that feature.

We should keep this in "Team's mindset" for our agile workflow: 
New Feature --> New Doc issue + New Test issue.

**Comment by manosnoam** [comment]
@aswinsuryan 
According to the Doc I should create the headless service with `--cluster-ip=''`, however this is not the correct syntax, and will fail:

```
$ oc expose deployment nginx-cl-b --name=nginx-cl-b --port=8080 --cluster-ip='' -n test-submariner-new

The Service "nginx-cl-b" is invalid: spec.clusterIP: Invalid value: "''": must be empty, 'None', or a valid IP address
(exit code: 1)

```

**Comment by manosnoam** [comment]
Apparently --cluster-set='None' is wrong too, we need to use --cluster-set=None (without single quotes)

**Comment by manosnoam** [comment]
On my env with Globalnet - the Headless service could not be exported:
https://qe-jenkins-csb-skynet.cloud.paas.psi.redhat.com/job/Submariner-OSP-AWS/797/Test-Report/

```
Status:
  Conditions:
    Last Transition Time:  2020-08-28T07:56:54Z
    Message:               Service doesn't have a global IP yet
    Reason:                ServiceGlobalIPUnavailable
    Status:                False
    Type:                  Initialized
```
@vthapar  
We should update Website docs, and point to https://github.com/submariner-io/submariner/issues/732

**Comment by tpantelis** [comment]
> On my env with Globalnet - the Headless service could not be exported:
> https://qe-jenkins-csb-skynet.cloud.paas.psi.redhat.com/job/Submariner-OSP-AWS/797/Test-Report/
> 
> ```
> Status:
>   Conditions:
>     Last Transition Time:  2020-08-28T07:56:54Z
>     Message:               Service doesn't have a global IP yet
>     Reason:                ServiceGlobalIPUnavailable
>     Status:                False
>     Type:                  Initialized
> ```
> 

That's odd - it should have printed "_Headless Services not supported with globalnet yet_" as that is checked prior to :the global IP:

      ```
 if a.globalnetEnabled && svcType == lighthousev2a1.Headless {
                klog.Infof("Headless Services not supported with globalnet yet")
                a.updateExportedServiceStatus(svcExport.Name, svcExport.Namespace, lighthousev2a1.ServiceExportInitialized,
                        corev1.ConditionFalse, invalidServiceType, "Headless Services not supported with Globalnet IP")
                return nil, false
        }

        if a.globalnetEnabled && getGlobalIpFromService(svc) == "" {
                klog.V(log.DEBUG).Infof("Service to be exported (%s/%s) doesn't have a global IP yet", svcExport.Namespace, svcExport.Name)
                a.updateExportedServiceStatus(svcExport.Name, svcExport.Namespace, lighthousev2a1.ServiceExportInitialized,
                        corev1.ConditionFalse, "ServiceGlobalIPUnavailable", "Service doesn't have a global IP yet")
                return nil, true
        }
```

That indicates the service wasn't headless.
