### ISSUE TITLE
Test Headless service discovery with Globalnet

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/lighthouse#273]
I opened this issue to track Subctl support for Lighthouse + Globalnet testing, when using Headless service.

On my env with Globalnet - the Headless service could not be exported:
https://qe-jenkins-csb-skynet.cloud.paas.psi.redhat.com/job/Submariner-OSP-AWS/797/Test-Report/

```
Status:
  Conditions:
    Last Transition Time:  2020-08-28T07:56:54Z
    Message:               Service doesn't have a global IP yet
    Reason:                ServiceGlobalIPUnavailable
    Status:                False
    Type:                  Initialized
```
@vthapar  
We should update Website docs, and point to https://github.com/submariner-io/submariner/issues/732

_Originally posted by @manosnoam in https://github.com/submariner-io/lighthouse/issues/271#issuecomment-682452206_

**Comment by nyechiel** [comment]
@manosnoam it's a valid bug, but we already have this tracked (https://github.com/submariner-io/submariner/issues/732) so I'd prefer if we close this for now.

**Comment by manosnoam** [comment]
I think it's best to have a test issue like this one, for every feature
(like #732), so we can track the feature tests and verification as well.

**Comment by manosnoam** [comment]
In 0.8.0 it's not supported yet.

**Comment by nyechiel** [comment]
> In 0.8.0 it's not supported yet.

Indeed, but this was not scoped for 0.8.1 either. Will revisit in 0.9.0 planning.

**Comment by manosnoam** [comment]
bump

**Comment by manosnoam** [comment]
Exporting headless service is now supported in Submariner v0.12, right @nyechiel ?

**Comment by nyechiel** [comment]
> Exporting headless service is now supported in Submariner v0.12, right @nyechiel ?

Yes. @yboaron @vthapar @sridhargaddam can help if you are seeing any issues or have further questions.
