### ISSUE TITLE
Ensure Lighthouse CoreDNS metrics are integrated

### ISSUE THREAD

**Issue by skitt** [submariner-io/lighthouse#276]
OpenShift’s default configuration includes CoreDNS metrics, but the Lighthouse CoreDNS server isn’t included. We should configure the cluster so that it is.

**Comment by nyechiel** [comment]
@skitt @maayanf24 before we close this, is there anything we need to document here?

**Comment by skitt** [comment]
> @skitt @maayanf24 before we close this, is there anything we need to document here?

I don’t think so, the metrics just show up with the other CoreDNS metrics...
