### ISSUE TITLE
ServiceExport conflict resolution

### ISSUE THREAD

**Issue by vthapar** [submariner-io/lighthouse#287]
When a Service is exported from multiple clusters, there can be conflicts between them. e.g. `serviceA` might be of type `ClusterIP` in `cluster1` but `Headless` in `cluster2`. Currently we don't have any means to detect and resolve such conflicts.

A solution must be able to do the following:
1. Detect there is a conflict.
2. Resolve conflict based on resolution strategy as described in MC S spec
3. Withdraw ServiceImport for service in conflict.
4. Set status for conflicting ServiceExport.

Spec: https://github.com/kubernetes/enhancements/tree/master/keps/sig-multicluster/1645-multi-cluster-services-api#constraints-and-conflict-resolution

**Comment by tpantelis** [comment]
bump

**Comment by nyechiel** [comment]
@vthapar are you still planning to look into this?
