### ISSUE TITLE
Remove domain "supercluster.local"

### ISSUE THREAD

**Issue by aswinsuryan** [submariner-io/lighthouse#289]
The "supercluster.local" domain shall be removed and from 0.7.0 only "clusterset.local" needs to be supported.

**Comment by vthapar** [comment]
Deployment in operator addressed by https://github.com/submariner-io/submariner-operator/pull/709

**Comment by manosnoam** [comment]
Verified in:
https://qe-jenkins-csb-skynet.cloud.paas.psi.redhat.com/job/debug_job/559/Test-Report/

```
$ oc exec netshoot-cl-a -n test-submariner -- ping -c 1 nginx-cl-b.test-submariner.svc.supercluster.local
ping: nginx-cl-b.test-submariner.svc.supercluster.local: Name does not resolve
```
