### ISSUE TITLE
submariner-lighthouse-agent cannot running

### ISSUE THREAD

**Issue by ssider** [submariner-io/lighthouse#306]
submariner-lighthouse-agent cannot running, it restarts all the time, and its logs show belows:

# kubectl -n submariner-operator logs -f submariner-lighthouse-agent-6695d59ccb-dnhfm
+ trap 'exit 1' SIGTERM SIGINT
+ LIGHTHOUSE_VERBOSITY=1
+ '[' '' == true ']'
+ DEBUG=-v=1
+ exec lighthouse-agent -v=1 -alsologtostderr
I0923 03:09:57.759822       1 main.go:34] AgentSpec: {zmx submariner-operator false}
W0923 03:09:57.759883       1 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0923 03:09:57.759970       1 main.go:51] Starting submariner-lighthouse-agent {zmx submariner-operator false}
F0923 03:10:39.369367       1 main.go:58] Failed to create lighthouse agent: Get "https://172.171.2.219:6443/apis/lighthouse.submariner.io/v2alpha1/namespaces/submariner-k8s-broker/serviceimports": dial tcp 172.171.2.219:6443: i/o timeout

it seems that it cannot connect to another cluster apiserver, but l can ping it ip well. so is there anybody can help me to sovle this prolems????? it confused me for days

**Comment by vthapar** [comment]
@ssider  are other submariner components `submariner-engine` etc. getting this error too? Can you provide details on steps followed for installation [helm vs operator], version of submariner, if operator then version of subctl etc.

**Comment by ssider** [comment]
using  subctl 0.6 and 0.6.1 have the same problems。l used kubeamd 1.8.4 to install kubernetes 1.8.4 version in local environment，and use subctl install submariner and then the submariner-lighthouse-agent restarted all the time,and its logs shows like above.
submariner-engine  didnot shows ant errors, but l find the two clusters have the same public ip route。l donnot know ifnot this factor  result in the problems

**Comment by vthapar** [comment]
@ssider Yeah, that is probably the issue then. You can look at logs of submariner-engine and they may have similar issues but doesn't go into error coz it likely doesn't validate access at startup. In lighthouse we try to check if we can access the resource on remote cluster or not.

**Comment by ssider** [comment]
> @ssider Yeah, that is probably the issue then. You can look at logs of submariner-engine and they may have similar issues but doesn't go into error coz it likely doesn't validate access at startup. In lighthouse we try to check if we can access the resource on remote cluster or not.

but it isnot report the access problems, it cannot connect to the broker cluster, and it the version 0.7.0 have the same probelms. it test it in local area network, and the whole clusters ( it have 3 clusters) have the same public ip, is it affect it ?

**Comment by ssider** [comment]
@vthapar

**Comment by aswinsuryan** [comment]
> in local area network, and the whole clusters ( it have 3 clusters) have the same public ip, is it affect it ?

@ssider If the clusters have overlapping IP address, you need to enable global net. But headless service does not work with global net right now. Since it is a test setup, would be better to have clusters with non-overlapping ips to try all features.

You could also deploy in kind  to get a feel of things 

https://submariner.io/getting-started/quickstart/kind/

**Comment by nyechiel** [comment]
@ssider please re-open and provide more info if this is still relevant.
