### ISSUE TITLE
Lighthouse: prefer the local cluster first, before routing to other remote clusters

### ISSUE THREAD

**Issue by nyechiel** [submariner-io/lighthouse#331]
Today, for the use case where a single ClusterIP service is deployed to multiple clusters for redundancy or scale, the Lighthouse plugin uses a round robin selection, so that traffic will be eventually served by all clusters in the ClusterSet.

Ideally, routing should be optimized for some sort of cost metric (e.g look at complete Service Topology information and prioritize traffic local to zone, region, etc), but until this concept matures in the upstream community I'd like to propose that we default to what we used to do with the original Lighthouse design and always prefer the local cluster first, before routing the traffic to other remote clusters (in a round-robin fashion).

I hope we can achieve this by enhancing the Lighthouse agent, and without modifying the MCS API.

**Comment by aswinsuryan** [comment]
We have a weight which is assigned to zero and unused. The weight can be increased to a higher value for the local cluster and can use weighted RR to select the IP. The plugin currently does not have the awareness of the cluster which it is running. But I think we could get it from one of the Submariner CRD. This will be required to assign a higher weight.

**Comment by danibachar** [comment]
Can I take this one?

**Comment by nyechiel** [comment]
> Aren't DNS requests from within the cluster will not get to the Lighthouse plugin?
> In any way, can I be assigned to it?

Sure, Daniel. Please sync with @aswinsuryan and @vthapar if you have any questions, but a PR is welcome.

**Comment by vthapar** [comment]
@danibachar We get local clusterid from gateway object here https://github.com/submariner-io/lighthouse/blob/master/pkg/gateway/controller.go#L175 and storing it in connection map. We can easily tweak the code here to handle it differently from remote endpoints.

**Comment by nyechiel** [comment]
@danibachar we want to support this feature in our upcoming release (v0.8). Do you have cycles to work on this in the next few weeks?

**Comment by danibachar** [comment]
@nyechiel Yep!
Plan to have a PR ready by the end of this weekend

**Comment by nyechiel** [comment]
@manosnoam FYI

**Comment by manosnoam** [comment]
Thanks @nyechiel 
Added E2E request: https://github.com/submariner-io/lighthouse/issues/365
