### ISSUE TITLE
Use the MCS SIG APIs instead of our own 

### ISSUE THREAD

**Issue by aswinsuryan** [submariner-io/lighthouse#336]
Use the MCS SIG APIs instead of our own 

[1]https://github.com/kubernetes-sigs/mcs-api

**Comment by aswinsuryan** [comment]
Install CRDs in operator.
https://github.com/submariner-io/lighthouse/issues/336

**Comment by nyechiel** [comment]
@manosnoam is there anything you need to test/automate before we can consider it done? AFAICT, this works as excepted, and E2E/subctl are using the new MCS CRDs now.

**Comment by manosnoam** [comment]
@aswinsuryan How can I validate it ?

**Comment by skitt** [comment]
> @aswinsuryan How can I validate it ?

@manosnoam see the Lighthouse-specific upgrade test, https://github.com/submariner-io/lighthouse/pull/400 — it checks that the MCS CRDs are used.

**Comment by aswinsuryan** [comment]
> > @aswinsuryan How can I validate it ?
> 
> @manosnoam see the Lighthouse-specific upgrade test, #400 — it checks that the MCS CRDs are used.

+1

**Comment by manosnoam** [comment]
On my env I use `oc get serviceexport` and it prints:
```
NAME         AGE
nginx-cl-b   52s
```

btw, with `oc describe serviceexport` I get very useful info now:
```
Name:         nginx-cl-b
Namespace:    test-submariner
Labels:       <none>
Annotations:  <none>
API Version:  multicluster.x-k8s.io/v1alpha1
Kind:         ServiceExport
Metadata:
  Creation Timestamp:  2020-12-20T06:38:50Z
  Generation:          1
  Resource Version:    23770185
  Self Link:           /apis/multicluster.x-k8s.io/v1alpha1/namespaces/test-submariner/serviceexports/nginx-cl-b
  UID:                 fcf70636-db07-426b-afe4-fe4660ed53b1
Status:
  Conditions:
    Last Transition Time:  2020-12-20T06:39:46Z
    Message:               Awaiting sync of the ServiceImport to the broker
    Reason:                AwaitingSync
    Status:                False
    Type:                  Valid
    Last Transition Time:  2020-12-20T06:39:47Z
    Message:               Service was successfully synced to the broker
    Reason:                
    Status:                True
    Type:                  Valid
Events:                    <none>
```
