### ISSUE TITLE
[E2E] Test remote services in a specific cluster explicitly

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/lighthouse#339]
Please add E2E test for remote services in a specific cluster explicitly.

That's the documentation:
https://submariner.io/quickstart/openshift/#verify

_Originally posted by @manosnoam in https://github.com/submariner-io/lighthouse/issue_comments/708315846_

**Comment by aswinsuryan** [comment]
I think we do not test this currently and we need add tests for this use case.

**Comment by pinikomarov** [comment]
@manosnoam the links are broken , can you repost them ? 

> 
> That's the documentation:
> https://submariner.io/quickstart/openshift/service_discovery/#verify
> 
> Originally posted by @manosnoam in https://github.com/submariner-io/lighthouse/issue_comments/708315846

**Comment by manosnoam** [comment]
@pinikomarov 
I've updated the comment. Please also note that there might be E2E test already:
https://github.com/submariner-io/lighthouse/blob/b37a1cbd457799e06de94d27a9adf28dcb10a377/pkg/serviceimport/map_test.go#L135

Please check if that indeed tests this $SUBJECT.
