### ISSUE TITLE
[E2E] Test service DNS on mutiple clusters returns diffrent IPs (Round Robin)

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/lighthouse#340]
Add test in E2E: 
When exporting same service name (with same DNS) on multiple clusters - It should return a different IP each request, according to the clusterIP (and Round Robin algorithm).

_Originally posted by @danibachar in https://github.com/submariner-io/lighthouse/issue_comments/703122297_

**Comment by aswinsuryan** [comment]
We have UT for this scenario but e2e is missing and we need to add it.

**Comment by nyechiel** [comment]
@aswinsuryan as discussed, this particular test will need to be skipped if 3 clusters are not available.
