### ISSUE TITLE
[E2E] test StatefulSets

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/lighthouse#341]
_Originally posted by @manosnoam in https://github.com/submariner-io/lighthouse/issue_comments/708367249_

**Comment by aswinsuryan** [comment]
@manosnoam We have these tests to cover statefulsets in e2e, do you think we miss any scenario here?

[1] https://github.com/submariner-io/lighthouse/blob/master/test/e2e/discovery/statefulsets.go

**Comment by manosnoam** [comment]
Thanks @aswinsuryan looks good to me.
