### ISSUE TITLE
Move Load Balancing logic out of map

### ISSUE THREAD

**Issue by danibachar** [submariner-io/lighthouse#342]
@vthapar @mangelajo @tpantelis @mkolesnik @skitt  - I would love to have your inputs regarding the following suggestion...

I think it is time to move the IP load balancing (selection) logic out of the map object. 
As we are moving forward, I think we should have a dedicated entity that is in charge of it.

The map object should just return the relevant IPs from a specific DNS query, and the load balancing mechanism should distributing the load between the IPs (of course per specific service).

I'm thinking of actually stripping away most of the map logic as follow:
map.go will have only the original properties: `key`, `clusterIPs`, `isHeadless`. Will act as the Store inteface + return the `clusterIPs` map for each query...

I will create a new package called loadbalancers under `plugin/lighthouse`. Which will hold the loadbalancers we shall offer. For now `Round-Robin`. In the near future `Weighted-Round-Robin` and eventually an optimized version.

Regarding IP resolving process - the handler will work as follow:
Query service import map -> which will return the `clusterIPs` -> checks local cluster for the service.
If appears -> returns its IP(s)
If not appear -> try selecting used the configured load balancer
If load balancer fails -> fall back to using EndpointSlice

This will happen of course [after](https://github.com/submariner-io/lighthouse/issues/331) which I plan to finish in the next few days...

In addition, from reading about the EndpointSlice part in the [multi-cluster kep](https://github.com/kubernetes/enhancements/tree/master/keps/sig-multicluster/1645-multi-cluster-services-api).
Does the current EndpointSlice implementation in the plugin comply with the guidelines? Don't we need to only use EndpointSlice which are created per SerivceExport?

**Comment by aswinsuryan** [comment]
> In addition, from reading about the Endpo



> @vthapar @mangelajo @tpantelis @mkolesnik @skitt - I would love to have your inputs regarding the following suggestion...
> 
> I think it is time to move the IP load balancing (selection) logic out of the map object.
> As we are moving forward, I think we should have a dedicated entity that is in charge of it.
> 
> The map object should just return the relevant IPs from a specific DNS query, and the load balancing mechanism should distributing the load between the IPs (of course per specific service).
> 
> I'm thinking of actually stripping away most of the map logic as follow:
> map.go will have only the original properties: `key`, `clusterIPs`, `isHeadless`. Will act as the Store inteface + return the `clusterIPs` map for each query...
> 
> I will create a new package called loadbalancers under `plugin/lighthouse`. Which will hold the loadbalancers we shall offer. For now `Round-Robin`. In the near future `Weighted-Round-Robin` and eventually an optimized version.
> 
> Regarding IP resolving process - the handler will work as follow:
> Query service import map -> which will return the `clusterIPs` -> checks local cluster for the service.
> If appears -> returns its IP(s)
> If not appear -> try selecting used the configured load balancer
Do we plan to check the g/w status here? Also with #351  we need to check if the service has active endpoints.
> If load balancer fails -> fall back to using EndpointSlice
Sorry, I am not clear about this step , is this for ClusterIP services? EndpointSlice will just have the enpointips right?
> 
> This will happen of course [after](https://github.com/submariner-io/lighthouse/issues/331) which I plan to finish in the next few days...
> 
> In addition, from reading about the EndpointSlice part in the [multi-cluster kep](https://github.com/kubernetes/enhancements/tree/master/keps/sig-multicluster/1645-multi-cluster-services-api).
> Does the current EndpointSlice implementation in the plugin comply with the guidelines? Don't we need to only use EndpointSlice which are created per SerivceExport?
Yes it complies with spec  with #351 we create endpointslices for clusterIp services too. The only this that would be different is we now just create one endpointslice per service per cluster, we do not limit the number of endpoint in a slice.
