### ISSUE TITLE
Lighthouse Prometheus Metrics

### ISSUE THREAD

**Issue by maayanf24** [submariner-io/lighthouse#349]
Add prometheus metrics for lighthouse
See here for details: https://github.com/submariner-io/submariner/issues/678

- [x] Number of imported services, number of exported services (probably doable as a metric in the resyncer, see https://github.com/submariner-io/admiral/issues/136) - [#468](https://github.com/submariner-io/lighthouse/pull/468)

- [ ] Health of a service in a remote cluster ( the number of active pods) 

- [ ] DNS results (query for A record mapped to IP address) (CoreDNS?)

- [ ] Who is accessing what and how frequently?

**Comment by nyechiel** [comment]
@maayanf24 just a reminder to also update the docs with the newly added Service Discovery metrics

**Comment by tpantelis** [comment]
bump

**Comment by nyechiel** [comment]
Closing old issue. Let's re-open if this is relevant and/or we have concrete user demand.
