### ISSUE TITLE
[E2E] Test service-discovery prefers local cluster before remote cluster

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/lighthouse#365]
Please add E2E test for feature https://github.com/submariner-io/lighthouse/issues/331

**Comment by nyechiel** [comment]
@vthapar @danibachar

**Comment by manosnoam** [comment]
@pinikomarov  please see the new tests that @vthapar is adding:
https://github.com/submariner-io/lighthouse/pull/356/files#diff-ff78d07fd1c06414d1a350b9af9c6300bb3bdba664ec1dc257d7b9108dcb72b7R529

**Comment by pinikomarov** [comment]
Hi @vthapar , 
I would like to create a test create plan for this e2e test :
- create service (local and non local) : 
https://github.com/submariner-io/lighthouse/blob/6c2ff9e0c96dbc2c5d0346eb0f9fcf7f4c3ea253/test/e2e/framework/framework.go#L64

- try ping or service access of some kind
https://github.com/submariner-io/lighthouse/blob/6c2ff9e0c96dbc2c5d0346eb0f9fcf7f4c3ea253/test/e2e/framework/framework.go#L110

z- check results: how to check the results 


@vthapar Hi , can you give me some pointers regarding the new service discovery test ?  i.e are the code references is correct ? should I be using different functions ? 
Thanks

**Comment by pinikomarov** [comment]
@tpantelis hey why was this closed ? I was planning to work on it ?

**Comment by skitt** [comment]
> @tpantelis hey why was this closed ? I was planning to work on it ?

@vthapar added an E2E test for this in https://github.com/submariner-io/lighthouse/pull/356.

**Comment by tpantelis** [comment]
> @tpantelis hey why was this closed ? I was planning to work on it ?

I didn't explicitly close this. It was auto-closed due to #356 being closed which was linked to this one.

**Comment by pinikomarov** [comment]
ok thanks
