### ISSUE TITLE
In ServiceImports include port number(s) of the services

### ISSUE THREAD

**Issue by sriharshaj70** [submariner-io/lighthouse#385]
**What would you like to be added**:
Currently, ServiceImports populated by submariner only includes IP addresses of the services.
However it would be good to include even the Port number(s) of services.
Port numbers are already part of the ServiceImport objecgt.

**Why is this needed**:
I am trying to see if we can somehow integrate OSM (openservice-mesh by Microsoft) with Submariner.
OSM `learns' about k8s services and programs envoy. Here, k8s is a `provider' and it provides a set of services (ServiceName, IP, Ports) to OSM within the cluster.

I was thinking of Submariner as another `provider' and can feed similar information to OSM about remote clusters.
So that services across clusters can seamlessly work.

**Comment by nyechiel** [comment]
bump

**Comment by vthapar** [comment]
@sriharshaj70 I'm targeting to get this done in current sprint. I had a few questions that I'd like to discuss with you. Reach out to me in slack when you can.
