### ISSUE TITLE
ServiceImports do not automatically re-appear if a service goes down and comes back up

### ISSUE THREAD

**Issue by sriharshaj70** [submariner-io/lighthouse#386]
**What happened**:
Here is the sequence :
1. Service is up and running
2. Do a subctl service export
3. Check corresponding ServiceImport is created
4. Bring down the Service
5. Bring up the service

**What you expected to happen**:
After (5), I expect the ServiceImport to be re-created automatically.
However, unless I delete the ServiceExport and re-recreate again, I don't see ServiceImport being automatically recreated.

**How to reproduce it (as minimally and precisely as possible)**:
Reproduction is straight-forward.

**Anything else we need to know?**:

**Environment**:
- Submariner version (use `subctl version`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tpantelis** [comment]
I assume in step 4 by "_Bring down the Service_" you mean you deleted it. In this case we delete the `ServiceImport` but the `ServiceExport` remains.  @vthapar this goes back to the discussion of whether we should delete the `ServiceExport` on service deletion. We would have to also handle service creation and recreate the `ServiceImport`  if a `ServiceExport` exists.

**Comment by vthapar** [comment]
@tpantelis I think would be better to recreate ServiceImport on Service creation than deleting ServiceExport, which is a user created object. Plan was always to support this use case, but wanted to have some cache for ServiceExports available. Making an API call to check ServiceExport on every service creation won't scale well.
