### ISSUE TITLE
Lighthouse E2E Failed to find pods for app nginx-ss

### ISSUE THREAD

**Issue by pinikomarov** [submariner-io/lighthouse#406]
https://qe-jenkins-csb-skynet.cloud.paas.psi.redhat.com/job/Submariner-OSP-AWS-Globalnet/39/#showFailuresLink

Stacktrace

/home/jenkins/go/src/github.com/submariner-io/lighthouse/test/e2e/discovery/statefulsets.go:20
Failed to retrieve ServiceExport. ServiceExportCondition Status is False
Unexpected error:
    <*errors.errorString | 0xc00042c640>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
occurred
/home/jenkins/go/pkg/mod/github.com/submariner-io/shipyard@v0.8.0-rc0/test/e2e/framework/framework.go:416

another failure : 
Standard Output

STEP: Creating namespace objects with basename "dataplane-gn-conn-nd"
STEP: Generated namespace "e2e-tests-dataplane-gn-conn-nd-dxpvm" in cluster "nmanos-cluster-a" to execute the tests in
STEP: Creating namespace "e2e-tests-dataplane-gn-conn-nd-dxpvm" in cluster "nmanos-cluster-b"
STEP: Creating a listener pod in cluster "nmanos-cluster-b", which will wait for a handshake over TCP
STEP: Pointing a service ClusterIP to the listener pod in cluster "nmanos-cluster-b"
Dec 13 08:54:22.573: INFO: Will send traffic to IP: 169.254.43.1
STEP: Creating a connector pod in cluster "nmanos-cluster-a", which will attempt the specific UUID handshake over TCP
STEP: Waiting for the connector pod "tcp-check-podb8jg8" to exit, returning what connector sent
Dec 13 08:56:42.810: INFO: Pod "tcp-check-podb8jg8" output:
nc: 169.254.43.1 (169.254.43.1:1234): Operation timed out
nc: 169.254.43.1 (169.254.43.1:1234): Operation timed out
nc: 169.254.43.1 (169.254.43.1:1234): Operation timed out

STEP: Waiting for the listener pod "tcp-check-listenerxv4gl" to exit, returning what listener sent
Dec 13 08:56:42.849: INFO: Pod "tcp-check-listenerxv4gl" output:
listening on 0.0.0.0:1234 ...
nc: timeout

Dec 13 08:56:42.849: INFO: Connector pod has IP: 10.166.45.241
STEP: Deleting namespace "e2e-tests-dataplane-gn-conn-nd-dxpvm" on cluster "nmanos-cluster-a"
STEP: Deleting namespace "e2e-tests-dataplane-gn-conn-nd-dxpvm" on cluster "nmanos-cluster-b"

still investigating..

**Comment by pinikomarov** [comment]
duration past : two days

**Comment by pinikomarov** [comment]
from the logs : 

src:
https://qe-jenkins-csb-skynet.cloud.paas.psi.redhat.com/job/Submariner-OSP-AWS-Globalnet/39/artifact/Submariner-OSP-AWS-Globalnet_Tests_13122020_0743.tar.gz / subm_pods.log

2020-12-13T07:37:35.280544044Z E1213 07:37:35.280432       1 ipam.go:216] service e2e-tests-discovery-gfc7z/nginx-ss requeued 2 times
[..]
       1 ipam.go:216] service e2e-tests-discovery-gfc7z/nginx-ss requeued 15 times
2020-12-13T07:40:19.598623395Z E1213 07:40:19.598566       1 ipam.go:216] service e2e-tests-discovery-gfc7z/nginx-ss requeued 16 times
2020-12-13T07:40:50.661418819Z E1213 07:40:50.661367       1 ipam.go:393] Error: handleRemovedService called for "", but globalIp annotation is missing.

2020-12-13T07:43:03.445069133Z E1213 07:43:03.445002       1 ipam.go:216] error retrieving submariner-ipam-controller object e2e-tests-discovery-gfc7z/nginx-ss: services "nginx-ss" not found

**Comment by pinikomarov** [comment]
@manosnoam on the other job that failed : 
https://qe-jenkins-csb-skynet.cloud.paas.psi.redhat.com/job/Submariner-OSP-AWS-Globalnet/38/Test-Report/

I see : 

1) 

• Failure [400.969 seconds]
[discovery] Test Service Discovery Across Clusters
/home/jenkins/go/src/github.com/submariner-io/lighthouse/test/e2e/discovery/service_discovery.go:22
  when there are active pods for a service in only one cluster
  /home/jenkins/go/src/github.com/submariner-io/lighthouse/test/e2e/discovery/service_discovery.go:50
    should not resolve the service on the cluster without active pods [It]
    /home/jenkins/go/src/github.com/submariner-io/lighthouse/test/e2e/discovery/service_discovery.go:51

    Failed to retrieve ServiceImport. Failed to find ServiceImport with IP 100.96.237.80
    Unexpected error:
        <*errors.errorString | 0xc0003f07d0>: {
            s: "timed out waiting for the condition",
        }
        timed out waiting for the condition
    occurred

and 2) 

• Failure [380.437 seconds]
[discovery] Test Stateful Sets Discovery Across Clusters
/home/jenkins/go/src/github.com/submariner-io/lighthouse/test/e2e/discovery/statefulsets.go:16
  when the number of active pods backing a stateful set changes
  /home/jenkins/go/src/github.com/submariner-io/lighthouse/test/e2e/discovery/statefulsets.go:39
    should only resolve the IPs from the active pods [It]
    /home/jenkins/go/src/github.com/submariner-io/lighthouse/test/e2e/discovery/statefulsets.go:40

    Failed to find pods for app nginx-ss. Status for pod "web-0" is Pending
    Unexpected error:
        <*errors.errorString | 0xc00042c640>: {
            s: "timed out waiting for the condition",
        }
        timed out waiting for the condition
    occurred

What do you think this is ?

**Comment by manosnoam** [comment]
This should be fixed by https://github.com/submariner-io/shipyard/pull/382

**Comment by manosnoam** [comment]
@vthapar Hi, the new [pr 382](https://github.com/submariner-io/shipyard/pull/382) does not fix e2e ngnix issue:
```
12:51:23 ===================================
12:51:23 Random Seed: 1607943083
12:51:23 Will run 27 of 30 specs
12:51:23 
12:51:23 STEP: Creating kubernetes clients
12:51:23 STEP: Creating lighthouse clients
12:51:23 STEP: Creating submariner clients

12:51:24 [discovery] Test Headless Service Discovery Across Clusters when a pod tries to resolve a headless service in a remote cluster 
12:51:24   should resolve the backing pod IPs from the remote cluster
12:51:24   /go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/lighthouse/test/e2e/discovery/headless_services.go:17
12:51:24 STEP: Creating namespace objects with basename "discovery"
12:51:24 STEP: Generated namespace "e2e-tests-discovery-rg6t4" in cluster "pkomarov-cluster-a" to execute the tests in
12:51:24 STEP: Creating namespace "e2e-tests-discovery-rg6t4" in cluster "default-cl2"
12:51:24 STEP: Creating an Nginx Deployment on on "default-cl2"

12:55:24 STEP: Deleting namespace "e2e-tests-discovery-rg6t4" on cluster "pkomarov-cluster-a"
12:55:24 STEP: Deleting namespace "e2e-tests-discovery-rg6t4" on cluster "default-cl2"
12:55:24 
12:55:24 ��� Failure [240.182 seconds]
12:55:24 [discovery] Test Headless Service Discovery Across Clusters
12:55:24 /go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/lighthouse/test/e2e/discovery/headless_services.go:13
12:55:24   when a pod tries to resolve a headless service in a remote cluster
12:55:24   /go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/lighthouse/test/e2e/discovery/headless_services.go:16
12:55:24     should resolve the backing pod IPs from the remote cluster [It]
12:55:24     /go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/lighthouse/test/e2e/discovery/headless_services.go:17
12:55:24 
12:55:24     Failed to find pods for app nginx-demo. Status for pod "nginx-demo-5598bbc5d7-qjmf7" is Pending
12:55:24     Unexpected error:
12:55:24         <*errors.errorString | 0xc000422070>: {
12:55:24             s: "timed out waiting for the condition",
12:55:24         }
12:55:24         timed out waiting for the condition
12:55:24     occurred
12:55:24 
12:55:24     /go/src/github.com/submariner-io/submariner-operator/vendor/github.com/submariner-io/shipyard/test/e2e/framework/framework.go:416
```

**Comment by nyechiel** [comment]
@manosnoam @pinikomarov 0.8.0-rc1 is tagged now and includes all the right fixes. I ran E2E with OCP on AWS and don't see any failures.
