### ISSUE TITLE
CI lighthouse test fails on: :get_running_pod_by_label 'app=submariner-lighthouse-agent'

### ISSUE THREAD

**Issue by pinikomarov** [submariner-io/lighthouse#426]

**Comment by pinikomarov** [comment]
CI job : 
https://qe-jenkins-csb-skynet.cloud.paas.psi.redhat.com/job/Submariner-OSP-AWS-No-Overlapping/132/

job test results : 
https://qe-jenkins-csb-skynet.cloud.paas.psi.redhat.com/job/Submariner-OSP-AWS-No-Overlapping/132/Test-Report/

failure is in the results : 

🎩︎[2021-01-03 09:07:41]
 Testing Lighthouse agent status on pkomarov-cluster-a

 [/home/jenkins/workspace/Submariner-OSP-AWS-No-Overlapping]

error: no matching resources found

Which breaks on : 
https://github.com/manosnoam/ocp-multi-cluster-tester/blob/701766b6813ae537d1dd9f5e0d2ff88e628b4828/setup_subm.sh#L2472

which runs : 
https://github.com/manosnoam/ocp-multi-cluster-tester/blob/701766b6813ae537d1dd9f5e0d2ff88e628b4828/helper_functions#L766

effectively: 
 ${OC} wait --timeout=3m --for=condition=ready pod ${namespace:+-n $namespace} -l $pod_label 'app=submariner-lighthouse-agent'

**Comment by pinikomarov** [comment]
This env still has a live env , (for a couple of hours from now )

access to the  pkomarov-cluster-a is at kubeconf in :
https://qe-jenkins-csb-skynet.cloud.paas.psi.redhat.com/job/Submariner-OSP-AWS-No-Overlapping/132/artifact/Submariner-OSP-AWS-No-Overlapping_Tests_03012021_0817.tar.gz

**Comment by pinikomarov** [comment]
I'll update once I debug this more...

**Comment by vthapar** [comment]
Getting following error trying to access resources on cluster-a

```
[vthapar@localhost Submariner-OSP-AWS-No-Overlapping_Tests_03012021_0817]$ kubectl get pods
Unable to connect to the server: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kube-apiserver-lb-signer")

```
On cluster-b which has proper kubeconf, it works fine
```
[vthapar@localhost Submariner-OSP-AWS-No-Overlapping_Tests_03012021_0817]$ kubectl get pods  -l app=submariner-lighthouse-agent -A
NAMESPACE             NAME                                           READY   STATUS    RESTARTS   AGE
submariner-operator   submariner-lighthouse-agent-85b7dd6fc9-qdj76   1/1     Running   0          92m

```

**Comment by pinikomarov** [comment]
Thanks @vthapar I'll try to get access to the aws cluster (hope the env was not deleted by now) and report back

**Comment by pinikomarov** [comment]
update : This was an old  env without aws access (cluster got deleted ) I'll reopen if this repeats
