### ISSUE TITLE
Service discovery between redundant clusters on local LAN

### ISSUE THREAD

**Issue by jfinch97** [submariner-io/lighthouse#470]
Hello, this is an issue / support request originating from a [post](https://groups.google.com/g/submariner-users/c/mSyku-V5ork) to the Submariner-users mailing list, which was [requested to be forwarded as an issue to this repo](https://groups.google.com/g/submariner-users/c/mSyku-V5ork/m/7u52lybfCgAJ).

The original issue is that when running subctl verification suite, I am consistently getting 7 failed tests from the service-discovery suite (logs attached).  In order to troubleshoot the root cause, the procedure below was suggested.
[test_suite_results.txt](https://github.com/submariner-io/lighthouse/files/6030884/test_suite_results.txt)

Using K8s v1.20.4, Submariner v0.8.1

Attempting to perform [manual verification of service discovery](https://submariner.io/getting-started/quickstart/kind/#verify-manually) per a [procedure recommended by Aswin](https://groups.google.com/g/submariner-users/c/mSyku-V5ork/m/Epp5wL7UCgAJ).  Logs resulting from this procedure are listed at the end.

**On local cluster (10.72.0.0/16):**
1. `kubectl create deployment nginx --image=nginx --namespace test`
2. `kubectl expose deployment nginx --port=80 --namespace test`
3. `./subctl export service --namespace test nginx`

**On Remote Cluster (10.66.0.0/16):**
1. `kubectl -n test  run --generator=run-pod/v1 tmp-shell --rm -i --tty --image quay.io/submariner/nettest -- /bin/bash`
2. `bash-5.0# dig nginx.test.svc.clusterset.local`

```
; <<>> DiG 9.16.6 <<>> nginx.test.svc.clusterset.local
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 56191
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: aeb2d12c4c32d7f6 (echoed)
;; QUESTION SECTION:
;nginx.test.svc.clusterset.local. IN	A

;; ANSWER SECTION:
nginx.test.svc.clusterset.local. 5 IN	A	10.72.2.247

;; Query time: 0 msec
;; SERVER: 10.67.0.10#53(10.67.0.10)
;; WHEN: Tue Feb 23 17:20:39 UTC 2021
;; MSG SIZE  rcvd: 119
```

**On local cluster:**
`kubectl delete serviceexports.multicluster.x-k8s.io --all`

**On remote cluster:**
same result from dig above

**On local cluster:**
`kubectl delete serviceexports.lighthouse.submariner.io --all`

**On remote cluster:**
same result from dig above

**On local cluster:**
kubectl delete namespace test

**On remote cluster:**
`bash-5.0# dig nginx.test.svc.clusterset.local`

```
; <<>> DiG 9.16.6 <<>> nginx.test.svc.clusterset.local
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 65
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 6e0a832b0e8aca26 (echoed)
;; QUESTION SECTION:
;nginx.test.svc.clusterset.local. IN	A

;; Query time: 4 msec
;; SERVER: 10.67.0.10#53(10.67.0.10)
;; WHEN: Tue Feb 23 17:32:31 UTC 2021
;; MSG SIZE  rcvd: 72
```
[manual_test_logs.txt](https://github.com/submariner-io/lighthouse/files/6030934/manual_test_logs.txt)

[edit Feb 23 1:40pm CST] CoreDNS logs as requested:
[coredns-log-local.txt](https://github.com/submariner-io/lighthouse/files/6031444/coredns-log-local.txt)
[coredns-log-remote.txt](https://github.com/submariner-io/lighthouse/files/6031445/coredns-log-remote.txt)

**Comment by vthapar** [comment]
@jfinch97

1. Which of the two clusters did you install broker in?
2. When you delete serviceexports, can you share output of `kubectl get svcim -A` on both clusters? If ServiceImports are not deleted at the time, take output again after a couple minutes.

**Comment by jfinch97** [comment]
@vthapar 
Broker is installed on clusterid=green (192.168.1.72 host IP, 10.71.x.x pod cidr, 10.72.x.x service cidr)

I will try the suggested kubectl comand, but when I try to delete serviceexports, it seems to have no effect.  I am not sure I am deleting serviceexports correctly- do you have any suggestion (my online searches haven't proven helpful).  Also, I wasn't sure which CRD to delete, serviceexport.multicluster or serviceexports.lighthouse.  Here is what I currently try, and the result:
```
john@green:~/.local/bin$ kubectl get crd
NAME                                      CREATED AT
clusters.submariner.io                    2021-02-22T02:33:15Z
endpoints.submariner.io                   2021-02-22T02:33:15Z
gateways.submariner.io                    2021-02-22T02:33:15Z
servicediscoveries.submariner.io          2021-02-22T02:33:51Z
serviceexports.lighthouse.submariner.io   2021-02-22T02:33:51Z
serviceexports.multicluster.x-k8s.io      2021-02-22T02:33:51Z
serviceimports.lighthouse.submariner.io   2021-02-22T02:33:15Z
serviceimports.multicluster.x-k8s.io      2021-02-22T02:33:15Z
submariners.submariner.io                 2021-02-22T02:33:43Z
john@green:~/.local/bin$
```
```
john@green:~/.local/bin$ kubectl delete crd serviceexports.multicluster.x-k8s.io
customresourcedefinition.apiextensions.k8s.io "serviceexports.multicluster.x-k8s.io" deleted
john@green:~/.local/bin$ 
```
I may be confusing it with something else, but I think sometimes I had been getting a response of "resource is empty" or similar wording.  Is this the correct command above?  If so, I will re-run and collect the outputs of `kubectl get svcim -A` from both clusters.

**Comment by nyechiel** [comment]
This might be the same issue as https://github.com/submariner-io/lighthouse/issues/475

**Comment by nyechiel** [comment]
> @vthapar
> Broker is installed on clusterid=green (192.168.1.72 host IP, 10.71.x.x pod cidr, 10.72.x.x service cidr)
> 
> I will try the suggested kubectl comand, but when I try to delete serviceexports, it seems to have no effect. I am not sure I am deleting serviceexports correctly- do you have any suggestion (my online searches haven't proven helpful). Also, I wasn't sure which CRD to delete, serviceexport.multicluster or serviceexports.lighthouse. Here is what I currently try, and the result:
> 
> ```
> john@green:~/.local/bin$ kubectl get crd
> NAME                                      CREATED AT
> clusters.submariner.io                    2021-02-22T02:33:15Z
> endpoints.submariner.io                   2021-02-22T02:33:15Z
> gateways.submariner.io                    2021-02-22T02:33:15Z
> servicediscoveries.submariner.io          2021-02-22T02:33:51Z
> serviceexports.lighthouse.submariner.io   2021-02-22T02:33:51Z
> serviceexports.multicluster.x-k8s.io      2021-02-22T02:33:51Z
> serviceimports.lighthouse.submariner.io   2021-02-22T02:33:15Z
> serviceimports.multicluster.x-k8s.io      2021-02-22T02:33:15Z
> submariners.submariner.io                 2021-02-22T02:33:43Z
> john@green:~/.local/bin$
> ```
> 
> ```
> john@green:~/.local/bin$ kubectl delete crd serviceexports.multicluster.x-k8s.io
> customresourcedefinition.apiextensions.k8s.io "serviceexports.multicluster.x-k8s.io" deleted
> john@green:~/.local/bin$ 
> ```
> 
> I may be confusing it with something else, but I think sometimes I had been getting a response of "resource is empty" or similar wording. Is this the correct command above? If so, I will re-run and collect the outputs of `kubectl get svcim -A` from both clusters.

`serviceexports.lighthouse` is deprecated (will be removed in 0.9); `serviceexport.multicluster` is being used.

**Comment by jfinch97** [comment]
@vthapar 
Here are the outputs of `kubectl get svcim -A` after deleting "serviceexports.multicluster.x-k8s.io"
```
john@green:~/.local/bin$ kubectl delete crd serviceexports.multicluster.x-k8s.io
customresourcedefinition.apiextensions.k8s.io "serviceexports.multicluster.x-k8s.io" deleted
john@green:~/.local/bin$ kubectl get svcim -A
No resources found
john@green:~/.local/bin$
```
Results from the remote cluster (blue):
```
john@blue:~$ kubectl get svcim -A
error: the server doesn't have a resource type "svcim"
john@blue:~
```
Edit- update... after 3 minutes or so I re-ran the `kubectl get svcim -A` command again and obtained this result.  Not sure if it is of consequence, but wanted to include.
```
john@blue:~$ kubectl get svcim -A
error: the server doesn't have a resource type "svcim"
john@blue:~$ kubectl get svcim -A
No resources found
john@blue:~$ 
```

**Comment by nyechiel** [comment]
This issue is now fixed in "devel": https://github.com/submariner-io/lighthouse/pull/480
@jfinch97 can you please try it out?

**Comment by jfinch97** [comment]
Confirmed success!  Thank you!  All tests passing:

![image](https://user-images.githubusercontent.com/79532316/110030395-46b78580-7cfb-11eb-9f8e-765d0779f85e.png)
![image](https://user-images.githubusercontent.com/79532316/110030255-196ad780-7cfb-11eb-840b-0ad2b3a6f528.png)
