### ISSUE TITLE
Epic: Support SRV record in Lighthouse  for exported services

### ISSUE THREAD

**Issue by aswinsuryan** [submariner-io/lighthouse#511]
**What would you like to be added**:
Support SRV record in Lighthouse  for exported services

**Why is this needed**:
SRV records help in discovering services by describing the protocol/s and address of headless services.

- [x] [Enhancement proposal](#525) 
- [x] [Support for SRV records](#526)
- [x] [Add e2e](#527)
- [x] [Update Docs](https://github.com/submariner-io/submariner-website/issues/510)

**Comment by raffaelespazzoli** [comment]
my use case, and it could be your test case, is to be able to deploy keycloak (RHSSO) across cluster with the infinispan DNS PING discovery mechanism configured (https://github.com/belaban/JGroups/blob/master/doc/manual/protocols.adoc#dns_ping), which essentially run an SRV query.

**Comment by aswinsuryan** [comment]
The SRV records of the below formats shall be supported. 

### Cluster IP Service

- \<portname\>.\<protocol\>.\<svc-name\>.\<svc-namespace\>.svc.clusterset.local -> will return the SRV record with the port number and domain name with matching port name and protocol from one of the joined clusters where the service is available. The clusters will be selected based on the Round Robin algorithm.

- \<portname\>.\<protocol\>.**\<cluster-name\>**.\<svc-name\>.\<svc-namespace\>.svc.clusterset.local -> will return SRV record from the cluster specified, if available with matching portname and protocol

If \<port-name\> and \<protocol\> is not specified one SRV record will be returned for each port configured for the service in the selected/specified cluster.

### Headless Service

- \<portname\>.\<protocol\>.\<svc-name\>.\<svc-namespace\>.svc.clusterset.local -> will return the SRV records  with port number and domain name for each backend pod with matching portname and protocol in every joined cluster where the service is available.

- \<portname\>.\<protocol\>.**\<cluster-name\>**.\<svc-name\>.\<svc-namespace\>.svc.clusterset.local -> will return the SRV records  with port number and domain name for each backend pod with matching portname and protocol, in the specified cluster.

If \<port-name\> and \<protocol\> is not specified one SRV record will be returned for each port configured for the service in the selected cluster or all clusters based on the query.

**Comment by tpantelis** [comment]
@Jaanki Why did you close this?

**Comment by Jaanki** [comment]
Must have closed it mistakenly :)
