### ISSUE TITLE
Failed to create lighthouse agent: cannot access the API server (lighthouse-agent pod don't start)

### ISSUE THREAD

**Issue by r-ricardo** [submariner-io/lighthouse#535]
**What happened**: I installed Submariner following the official documentation, but there is an error with the lighthouse-agent. Submariner was installed correctly using the subctl tool in two OpenShift clusters, no errors occur during installation, but the lighthouse-agent pod crash immediately after start in both clusters. The rest of the pods associated with Submariner operator are running without problem.

**What you expected to happen**: The lighthouse-agent start without error

**How to reproduce it (as minimally and precisely as possible)**: Install Submariner in Openshift as documented in the official site of Submariner.

**Anything else we need to know?**:
lighthouse-agent pod output the following error in the logs

`I0514 03:32:23.514511   1 main.go:68] Arguments: [/usr/local/bin/lighthouse-agent -alsologtostderr -v=1]`
`I0514 03:32:23.514583   1 main.go:69] AgentSpec: {xxxxxx submariner-operator true}`
`w0514 03:32:23.514649   1 client_config.go:543] Neither --kubeconfig nor --master was specified. Using the inClusterConfig. This might not work.`
`I0514 03:32:44.517269   1 main.go:96] Starting submariner-lighthouse-agent {xxxxx submariner-operator true}`
`F0514 03:32:44.654136  1 main.go:113] Failed to create lighthouse agent: cannot access the API server "xxxxxxx": GET "xxxxxx": x509: certificate signed by uknown authority`

**Environment**:
- Submariner version (use `subctl version`): v0.9.0
- Kubernetes version (use `kubectl version`): v1.19.0+263ee0d
- Diagnose information (use `subctl diagnose all`): 
`OK Chcking Submariner support for the Kubernetes version used in cluster "xxxxxx"`
`OK The Kubernetes version meets Submariner's requirements`
`OK Retrieving Submariner resource from "xxxxxxx"`
`Error Checking Submariner support for the CNI network plugin in cluster "xxxxxxx"`
`Error The detected CNI network plugin ("Calico") is not supported by Submariner. Supported network plugins: [generic canal-flannel weave-net OpenShift]`
`Skipping tunnel firewall check as it requires two kubeconfig. Please run "subctl diagnose firewall tunnel" command manually`
`OK Retrieving Submariner resource from "xxxxxxxxxx"`
- Gather information (use `subctl gather`)
`Found 1 pods matching label selector "app=submariner-gateway"`
`Found 6 pods matching label selector "app=submariner-routeagent"`
`Found 1 pods matching label selector "app=submariner-global-net"`
`Found 0 pods matching label selector "app=submariner-networkplugin-syncer"`
- Cloud provider or hardware configuration: OpenShift 4.6.23 over IBM Cloud
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g `uname -a`):
- Install tools:
- Others:

**Comment by cwillia-ibm** [comment]
I am seeing the same exact problem in my cluster as well
Same environment:
Submariner 0.9.0
IBM Cloud w/ OpenShift 4.6.23

**Comment by cwillia-ibm** [comment]
I tried another deployment using the devel subctl and am seeing this for the diagnose all

 ✓ Checking Submariner support for the Kubernetes version used in cluster "*******" 
 ✓ The Kubernetes version meets Submariner's requirements

 ✓ Retrieving Submariner resource from "************" 

 ✗ Checking Submariner support for the CNI network plugin in cluster "**********"
 ✗ The detected CNI network plugin ("Calico") is not supported by Submariner. Supported network plugins: [generic canal-flannel weave-net OpenShiftSDN OVNKubernetes calico]

I noticed that "calico" is in the supported network plugins but it didn't recognize "Calico"
