### ISSUE TITLE
Switch EndpointSlices to discovery.k8s.io/v1

### ISSUE THREAD

**Issue by skitt** [submariner-io/lighthouse#576]
This will need to be done by the summer of 2022.

In K8s 1.20, discovery.k8s.io/v1 was added. v1beta1 will no longer be served starting with 1.25, so before that happens we need to migrate to /v1 (assuming we no longer need to support versions before 1.20).

This is also a blocker for the migration to CoreDNS 1.8.4 which relies on /v1.

**Comment by nyechiel** [comment]
@skitt how important is this for 0.12?

**Comment by skitt** [comment]
> @skitt how important is this for 0.12?

It isn’t; we’ll need to address this by this summer (the planned release date for K8s 1.25).

**Comment by mkolesnik** [comment]
We should address it in 0.13

**Comment by yboaron** [comment]
Maybe (for 0.12) we should avoid appending the warning to lighthouseagent/coredns pods logs every few minutes?

[yboaron@fedora submariner-operator]$ kubectl logs submariner-lighthouse-agent-64cb4cfd47-xk8w4   -n submariner-operator 
I0307 10:55:06.911728       1 main.go:70] Arguments: [/usr/local/bin/lighthouse-agent -alsologtostderr -v=2]
I0307 10:55:06.911768       1 main.go:71] AgentSpec: {cluster2 submariner-operator false false}
W0307 10:55:06.911812       1 client_config.go:608] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0307 10:55:06.925602       1 main.go:98] Starting submariner-lighthouse-agent {cluster2 submariner-operator false false}
W0307 10:55:06.953166       1 warnings.go:67] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
I0307 10:55:06.953782       1 agent.go:164] Starting Agent controller
W0307 10:55:07.156821       1 warnings.go:67] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
W0307 10:55:07.157995       1 warnings.go:67] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
W0307 10:55:07.256663       1 warnings.go:67] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
W0307 10:55:07.257307       1 warnings.go:67] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
I0307 10:55:07.457142       1 agent.go:208] Agent controller started
W0307 11:02:14.260840       1 warnings.go:67] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
W0307 11:03:26.163020       1 warnings.go:67] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
W0307 11:07:43.264044       1 warnings.go:67] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
W0307 11:12:30.163477       1 warnings.go:67] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
W0307 11:15:03.267792       1 warnings.go:67] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
W0307 11:18:30.166265       1 warnings.go:67] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
W0307 11:22:54.270259       1 warnings.go:67] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
W0307 11:27:15.169882       1 warnings.go:67] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
W0307 11:30:31.273342       1 warnings.go:67] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
W0307 11:37:07.173869       1 warnings.go:67] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
W0307 11:38:58.276545       1 warnings.go:67] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
W0307 11:43:30.176446       1 warnings.go:67] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
W0307 11:45:14.279648       1 warnings.go:67] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
W0307 11:50:43.287818       1 warnings.go:67] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
W0307 11:52:54.180315       1 warnings.go:67] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
W0307 11:56:49.288273       1 warnings.go:67] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
W0307 11:59:27.182368       1 warnings.go:67] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
W0307 12:05:28.295949       1 warnings.go:67] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
W0307 12:08:56.186356       1 warnings.go:67] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
[yboaron@fedora submariner-operator]$
