### ISSUE TITLE
Resolve To Remote IP issue

### ISSUE THREAD

**Issue by tarekesmail** [submariner-io/lighthouse#582]
**What happened**:
After creating the example in user guide, the curl request failing for 5 times and success for 2 or 3 
**What you expected to happen**:
I think there are some problem in connectivity
**How to reproduce it (as minimally and precisely as possible)**:
just follow up the user guide in submariner
**Anything else we need to know?**:

**Environment**:
- Submariner version (use `subctl version`): subctl version: v0.9.1 
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`)
- Cloud provider or hardware configuration:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g `uname -a`):
- Install tools:
- Others:

**Comment by sridhargaddam** [comment]
I'm not sure if this is still reproducible with latest builds. Closing this for now, please re-open or let us know if this is still an issue.
