### ISSUE TITLE
Service discovery e2e failing when cluster-id is long

### ISSUE THREAD

**Issue by aswinsuryan** [submariner-io/lighthouse#593]
**What happened**:
```
The service discovery tests are failing when used the cluster-name,  cluster-a-openshift-sdn-1
[Fail] [discovery] Test Headless Service Discovery Across Clusters when a pod tries to resolve a headless service in a remote cluster [It] should resolve the backing pod IPs from the remote cluster 
github.com/submariner-io/shipyard@v0.10.0-rc1/test/e2e/framework/framework.go:490

[Fail] [discovery] Test Headless Service Discovery Across Clusters when a pod tries to resolve a headless service which is exported locally and in a remote cluster [It] should resolve the backing pod IPs from both clusters 
github.com/submariner-io/shipyard@v0.10.0-rc1/test/e2e/framework/framework.go:490

[Fail] [discovery] Test Headless Service Discovery Across Clusters when the number of active pods backing a service changes [It] should only resolve the IPs from the active pods 
github.com/submariner-io/shipyard@v0.10.0-rc1/test/e2e/framework/framework.go:490

[Fail] [discovery] Test Headless Service Discovery Across Clusters when a pod tries to resolve a headless service in a specific remote cluster by its cluster name [It] should resolve the backing pod IPs from the specified remote cluster 
github.com/submariner-io/shipyard@v0.10.0-rc1/test/e2e/framework/framework.go:490

Ran 23 of 41 Specs in 1598.263 seconds
FAIL! -- 19 Passed | 4 Failed | 0 Pending | 18 Skipped
[] E2E failed
```

The logs are showing this error 

`E0804 09:28:50.215547       1 queue.go:104] Endpoints -> EndpointSlice: Failed to process object with key "e2e-tests-discovery-gs6px/nginx-headless": error creating &unstructured.Unstructured{Object:map[string]interface {}{"addressType":"IPv4", "apiVersion":"discovery.k8s.io/v1beta1", "endpoints":[]interface {}{map[string]interface {}{"addresses":[]interface {}{"10.129.2.36"}, "conditions":map[string]interface {}{"ready":true}, "hostname":"nginx-demo-b8f8b4fc6-zq9rg", "topology":map[string]interface {}{"kubernetes.io/hostname":"ip-10-0-153-11.us-east-2.compute.internal"}}}, "kind":"EndpointSlice", "metadata":map[string]interface {}{"labels":map[string]interface {}{"endpointslice.kubernetes.io/managed-by":"lighthouse-agent.submariner.io", "lighthouse.submariner.io/sourceCluster":"cluster-a-openshift-sdn-1", "lighthouse.submariner.io/sourceName":"nginx-headless", "lighthouse.submariner.io/sourceNamespace":"e2e-tests-discovery-gs6px", "multicluster.kubernetes.io/service-name":"nginx-headless-e2e-tests-discovery-gs6px-cluster-a-openshift-sdn-1"}, "name":"nginx-headless-cluster-a-openshift-sdn-1", "namespace":"e2e-tests-discovery-gs6px"}, "ports":[]interface {}{map[string]interface {}{"name":"http", "port":80, "protocol":"TCP"}}}}: EndpointSlice.discovery.k8s.io "nginx-headless-cluster-a-openshift-sdn-1" is invalid: metadata.labels: Invalid value: "nginx-headless-e2e-tests-discovery-gs6px-cluster-a-openshift-sdn-1": must be no more than 63 characters`

**What you expected to happen**:
Long cluster-id needs to be supported and tests should pass.

**How to reproduce it (as minimally and precisely as possible)**:

Run e2e using a cluster name of cluster-a-openshift-sdn-1

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by tpantelis** [comment]
@sridhargaddam recently discovered this issue elsewhere as well and pushed PRs to limit the length to 63:

https://github.com/submariner-io/submariner-operator/pull/1518
https://github.com/submariner-io/submariner/pull/1511

**Comment by vthapar** [comment]
> @sridhargaddam recently discovered this issue elsewhere as well and pushed PRs to limit the length to 63:
> 
> [submariner-io/submariner-operator#1518](https://github.com/submariner-io/submariner-operator/pull/1518)
> [submariner-io/submariner#1511](https://github.com/submariner-io/submariner/pull/1511)

It will not be enough. We create distributed objects like ServiceImport and Endpoint slices as combination of ClusterId, Service name and Service Namespace. Just adding a check for clusterId will not be enough. This is something that we've known and we need to document. Other option would be to not construct name of created objects from source objects and use a partial uuid for uniqueness.

**Comment by aswinsuryan** [comment]
> > @sridhargaddam recently discovered this issue elsewhere as well and pushed PRs to limit the length to 63:
> > [submariner-io/submariner-operator#1518](https://github.com/submariner-io/submariner-operator/pull/1518)
> > [submariner-io/submariner#1511](https://github.com/submariner-io/submariner/pull/1511)
> 
> It will not be enough. We create distributed objects like ServiceImport and Endpoint slices as combination of ClusterId, Service name and Service Namespace. Just adding a check for clusterId will not be enough. This is something that we've known and we need to document. Other option would be to not construct name of created objects from source objects and use a partial uuid for uniqueness.

We could also consider using a hash of cluster-id+namespace, which ensures that length is within the limits

**Comment by tpantelis** [comment]
> > > @sridhargaddam recently discovered this issue elsewhere as well and pushed PRs to limit the length to 63:
> > > [submariner-io/submariner-operator#1518](https://github.com/submariner-io/submariner-operator/pull/1518)
> > > [submariner-io/submariner#1511](https://github.com/submariner-io/submariner/pull/1511)
> > 
> > 
> > Other option would be to not construct name of created objects from source objects and use a partial uuid for uniqueness.
> 
> We could also consider using a hash of cluster-id+namespace, which ensures that length is within the limits

I think UUID would be ideal or, better yet, use the K8s name generation functionality.
