### ISSUE TITLE
Provide a Stable Network ID for StatefulSets used with headless service

### ISSUE THREAD

**Issue by mkimuram** [submariner-io/lighthouse#601]
**What would you like to be added**:
As described [here](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-network-id), it is useful if each pod in Statefulset can be accessed via `web-{0..N-1}.nginx.default.svc.cluster.local` inside a single cluster. Similarly, for clusters with submariner and lighthouse, it will be useful if each pod in Statefulset can be accessed via `web-{0..N-1}.nginx.default.svc.clusterset.local` from the other cluster.

**Why is this needed**:
With this feature, users will be able to access to the specific pod that they are interested in by using DNS name.

**Comment by mkimuram** [comment]
According to [the spec](https://github.com/submariner-io/enhancements/blob/devel/lighthouse/srv-records.md#headless-service), DNS name can be specified by using `<portname>.<protocol>.<svc-name>.<svc-namespace>.svc.clusterset.local` or `<portname>.<protocol>.<cluster-name>.<svc-name>.<svc-namespace>.svc.clusterset.local` formats with or without `<portname>` and `<protocol>` ommited.
Therefore, we will need to consider how to avoid conflicts (Users won't be allow to ommit fields when specifying a specific pod?).

**Comment by mkimuram** [comment]
Sorry. I found a description for this feature, [here](https://submariner.io/getting-started/quickstart/openshift/globalnet/#verify-statefulsets).

> To access an individual pod in a specific cluster, prefix the query with <pod-hostname>.<cluster-id>:
> ```
> curl web-0.cluster-a.nginx-ss.default.svc.clusterset.local:8080
> ```

I confirmed that I can access to individual pod with `cluster-id` like `web-{0..N-1}.cluster-b.nginx.default.svc.clusterset.local`.

```
nslookup web-0.cluster-b.nginx.default.svc.clusterset.local 
Server:         242.0.255.251
Address:        242.0.255.251#53

Name:   web-0.cluster-b.nginx.default.svc.clusterset.local
Address: 242.1.255.251
```
While it doesn't work without `cluster-id` like `web-{0..N-1}.nginx.default.svc.clusterset.local`.
```
nslookup web-0.nginx.default.svc.clusterset.local 
Server:         242.0.255.251
Address:        242.0.255.251#53

** server can't find web-0.nginx.default.svc.clusterset.local: SERVFAIL
```

Therefore, this feature has already been implemented and documented as a part of examples.
I think that it would be nice if we can clearly document this kind of specification somewhere, not as just an example.

**Comment by skitt** [comment]
This is specified in the [multi-cluster services API](https://github.com/kubernetes/enhancements/tree/master/keps/sig-multicluster/1645-multi-cluster-services-api). Is that sufficient?

**Comment by mkimuram** [comment]
Thank you for sharing the URL.
As you mentioned, it clearly describes this behavior:

> ```Pods backing a clusterset service may be addressed individually using the <hostname>.<clustername>.<svc>.<ns>.svc.clusterset.local format.```

And it is linked from https://submariner.io/getting-started/architecture/service-discovery/ -> https://github.com/kubernetes-sigs/mcs-api . Therefore, it will be sufficient.

Closing this issue.
