### ISSUE TITLE
Service without selector should be resolvable

### ISSUE THREAD

**Issue by mkimuram** [submariner-io/lighthouse#603]
**What happened**:
Service without selector can't be resolved.

**What you expected to happen**:
Service without selector can be resolved.

**How to reproduce it (as minimally and precisely as possible)**:
- Deploy submariner with globalnet enabled
- Create service without selector, export the service, and try to resolve the service
```
cat << EOF | kubectl apply -f - 
apiVersion: v1
kind: Service
metadata:
  name: ext-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
EOF

cat << EOF | kubectl apply -f - 
apiVersion: v1
kind: Endpoints
metadata:
  name: ext-service
subsets:
  - addresses:
      - ip: 192.168.122.111
    ports:
      - port: 80
EOF

cat << EOF | kubectl apply -f - 
kind: ServiceExport
apiVersion: multicluster.x-k8s.io/v1alpha1
metadata:
 name: ext-service
EOF

kubectl get svc,endpoints,serviceexport,globalingressip ext-service
NAME                  TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
service/ext-service   ClusterIP   10.43.65.198   <none>        80/TCP    82s

NAME                    ENDPOINTS            AGE
endpoints/ext-service   192.168.122.111:80   80s

NAME                                              AGE
serviceexport.multicluster.x-k8s.io/ext-service   78s

NAME                                        IP
globalingressip.submariner.io/ext-service   242.1.255.249

kubectl run --rm -i --tty client --image=registry.access.redhat.com/ubi8/ubi-minimal:latest -- bash
[root@client /]# microdnf install -y bind-utils
[root@client /]# nslookup ext-service.default.svc.clusterset.local
Server:         10.43.0.10
Address:        10.43.0.10#53

*** Can't find ext-service.default.svc.clusterset.local: No answer
[root@client /]# exit

```

**Anything else we need to know?**:

Service __with__ selector can be resolved in the same environment. It seems that endpointslice with `endpointslice.kubernetes.io/managed-by: lighthouse-agent.submariner.io` label is not created for service __without__ selector.

```
kubectl get endpointslice 
NAME                ADDRESSTYPE   PORTS   ENDPOINTS                                   AGE
kubernetes          IPv4          6443    192.168.122.27                              25h
http-vd2nt          IPv4          80      10.42.0.14                                  25h
http-cluster-b      IPv4          80      10.42.0.14                                  25h
nginx-72f6n         IPv4          80      10.42.0.16,10.42.0.18,10.42.0.20            22h
nginx-cluster-b     IPv4          80      242.1.255.251,242.1.255.252,242.1.255.250   21h
ext-service-hr8mk   IPv4          80      192.168.122.111                             42m
```

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration: kvm guest 
- Install tools: subctl (devel branch `curl -Ls https://get.submariner.io | VERSION="devel" bash -s -`)
- Others:

**Comment by sridhargaddam** [comment]
@vthapar @aswinsuryan is this use-case supported with LH?

**Comment by mangelajo** [comment]
Can we test it with an EndpointSlice instead? may be it would work. I'm not sure on the internals of lighthouse in this are.

**Comment by vthapar** [comment]
@sridhargaddam We currently don't support this use case and iirc you should be able to see corresponding error in ServiceExport status. We didn't support at the time coz didn't have a use case. Now that we do, can be easily done. Note that it would still require user to create Endpoint with some IP for it to work. And as @mangelajo pointed out, creating endpointslice manually should work as a workaround till we add support in lighthouse.

**Comment by mangelajo** [comment]
@vthapar do we still support "Endpoints" I don't see code about that in lighthouse.

**Comment by aswinsuryan** [comment]
@mangelajo we currently create "Lighthouse EndpointSlices" from endpoint objects of service. Here we need to create these "Lighthouse EndpointSlices"  manually.

**Comment by mangelajo** [comment]
hmmm, Where is the Endpoint read in lighthouse code?, I could not find that.

In the end if he creates the Endpoint manually, I think it's not different from automatically created endpoint.

**Comment by vthapar** [comment]
@mangelajo We have this check in code before we create listener for Endpoints:

https://github.com/submariner-io/lighthouse/blob/devel/pkg/agent/controller/serviceimport.go#L124

```
	if service.Spec.Selector == nil {
		klog.Errorf("The service %s/%s without a Selector is not supported", serviceNameSpace, serviceName)
		return false
	}
```

**Comment by mkimuram** [comment]
@vthapar 

Thank you for your advice.

Manually creating endpointslice worked to point to the __Cluster IP__ by below way.
Next step will be to make it point to __endpoint address__, not to Cluster IP.
Will it be expected to work just to change the service to headless service or any other changes needed, like changing fields in the endpointslice?

```
cat << EOF | kubectl apply -f - 
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  labels:
    endpointslice.kubernetes.io/managed-by: lighthouse-agent.submariner.io
    lighthouse.submariner.io/sourceCluster: cluster-b
    lighthouse.submariner.io/sourceName: ext-service
    lighthouse.submariner.io/sourceNamespace: default
    multicluster.kubernetes.io/service-name: ext-service-default-cluster-b
  name: ext-service-cluster-b
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Endpoints
    name: ext-service
    uid: c282ad73-1807-45a2-a408-837a5315748d
ports:
- name: ""
  port: 80
  protocol: TCP
addressType: IPv4
endpoints:
- addresses:
  - 192.168.122.111
  conditions:
    ready: true
EOF

kubectl run --rm -i --tty client --image=registry.access.redhat.com/ubi8/ubi-minimal:latest -- bash
[root@client /]# microdnf install -y bind-utils
[root@client /]# nslookup ext-service.default.svc.clusterset.local
Server:		10.43.0.10
Address:	10.43.0.10#53

Name:	ext-service.default.svc.clusterset.local
Address: 10.43.65.198
[root@client /]# exit


kubectl get svc ext-service
NAME          TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
ext-service   ClusterIP   10.43.65.198   <none>        80/TCP    8d
```

**Comment by vthapar** [comment]
@mkimuram In case of headless service, endpoint slice has IPs of pods backing the service. If any IP that you want it to return, will have to be added to endpointslice. ServiceIP rarely changes but pod IPs change more frequently. Based on your actual use case it may or may not be an issue. Note that for headlessservice you may also need to add pod hostname information to addresses. You can create and export a headless service with selector to get reference endpointslice.

**Comment by mkimuram** [comment]
> Next step will be to make it point to endpoint address, not to Cluster IP.
> Will it be expected to work just to change the service to headless service or any other changes needed, like changing fields in the endpointslice?

Sorry. I noticed that we just need to change endpoint address to globalIngressIP for it.
That's what headless service with selector is doing.

**Comment by mkimuram** [comment]
> In case of headless service, endpoint slice has IPs of pods backing the service. 
> If any IP that you want it to return, will have to be added to endpointslice.
> ServiceIP rarely changes but pod IPs change more frequently. 
> Based on your actual use case it may or may not be an issue. 

My use case for "service with selector" is the same to what is described [here](https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors),  expect that it is in the multi-cluster context. Also, the use case for "headless service with selector" is the same to what is described [here](https://kubernetes.io/docs/concepts/services-networking/service/#without-selectors), expect that it is in the multi-cluster context. (And with the latter feature, I'm expecting that it provides an identity of an external application by globalIngressIP for both source IP and destination IP, when used with globalnet).

A pod in any clusters is expected to be able to access to external application via lighthouse's DNS name. In other word, if only talking about lighthouse, lighthouse's DNS name for such external endpoints should be resolvable to the external IP or the globalIngressIP.

Therefore, as for the frequency of changing endpointslice in this use case, it isn't expected to be changed frequently. Because endpoint IPs for external applications will be more consistent than those of pods backing the service.

**Comment by anfredette** [comment]
This can be assigned to me.
