### ISSUE TITLE
Service Discovery tests fail with k8s 1.22/OpenShift 4.9

### ISSUE THREAD

**Issue by maayanf24** [submariner-io/lighthouse#627]
**What happened**:
While running E2e tests with k8s 1.22, all tests are failing.
Found this error in the logs:

`E1014 14:06:23.666358       1 queue.go:104] Endpoints -> EndpointSlice: Failed to process object with key "e2e-tests-discovery-2g7qd/nginx-ss": error creating &unstructured.Unstructured{Object:map[string]interface {}{"addressType":"IPv4", "apiVersion":"discovery.k8s.io/v1beta1", "endpoints":[]interface {}{map[string]interface {}{"addresses":[]interface {}{"10.132.2.58"}, "conditions":map[string]interface {}{"ready":true}, "hostname":"web-0", "topology":map[string]interface {}{"kubernetes.io/hostname":"ip-10-0-133-151.us-east-2.compute.internal"}}, map[string]interface {}{"addresses":[]interface {}{"10.133.2.19"}, "conditions":map[string]interface {}{"ready":true}, "hostname":"web-1", "topology":map[string]interface {}{"kubernetes.io/hostname":"ip-10-0-215-91.us-east-2.compute.internal"}}, map[string]interface {}{"addresses":[]interface {}{"10.135.0.191"}, "conditions":map[string]interface {}{"ready":true}, "hostname":"web-2", "topology":map[string]interface {}{"kubernetes.io/hostname":"ip-10-0-189-78.us-east-2.compute.internal"}}}, "kind":"EndpointSlice", "metadata":map[string]interface {}{"labels":map[string]interface {}{"endpointslice.kubernetes.io/managed-by":"lighthouse-agent.submariner.io", "lighthouse.submariner.io/sourceCluster":"cluster-b", "lighthouse.submariner.io/sourceName":"nginx-ss", "lighthouse.submariner.io/sourceNamespace":"e2e-tests-discovery-2g7qd"}, "name":"nginx-ss-cluster-b", "namespace":"e2e-tests-discovery-2g7qd"}, "ports":[]interface {}{map[string]interface {}{"name":"http", "port":80, "protocol":"TCP"}}}}: endpointslices.discovery.k8s.io "nginx-ss-cluster-b" is forbidden: endpoint address 10.132.2.58 is not allowed`

**What you expected to happen**:
E2E tests pass

**How to reproduce it (as minimally and precisely as possible)**:
`subctl verify --only service-discovery,connectivity --verbose --kubecontexts cluster-a, cluster-b`

**Anything else we need to know?**:

**Environment**:
oc version
Client Version: 4.9.0-0.nightly-2021-09-09-145014
Server Version: 4.9.0-0.nightly-2021-09-09-145014
Kubernetes Version: v1.22.0-rc.0+75ee307

- Diagnose information (use `subctl diagnose all`):
- 
- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration:
- AWS
- Install tools:
- Others:

**Comment by vthapar** [comment]
@maayanf24 Can you share the gather logs output? Want to check if this error shows up only on cluster where we're running broker or all data clusters.

**Comment by maayanf24** [comment]
@vthapar sure

[submariner-20211018093302.tar.gz](https://github.com/submariner-io/lighthouse/files/7363616/submariner-20211018093302.tar.gz)

**Comment by aswinsuryan** [comment]
From Openshift 4.9 we have extra validation which allows only service account which has endpointslices/restricted to create an endpointslices that endpoint IP same as cluster's Pod CIDR. So we need to grant this submariner-lighthouse-agent cluster role.

If the broker cluster and data cluster resides together, the broker roles need this permission as well as it will have endpointslices synced from the same cluster.
