### ISSUE TITLE
subctl expose service - supports type Loadbalancer?

### ISSUE THREAD

**Issue by ccwalterhk** [submariner-io/lighthouse#662]
### Does subctl expose service supports type Loadbalancer?

```
--> Created earth-service with LoadBalancer type in cluster b.

walter@k3-subctl-m1:~$ kubectl  --kubeconfig kubeconfig.cluster-b get service
NAME            TYPE           CLUSTER-IP       EXTERNAL-IP                              PORT(S)          AGE
kubernetes      ClusterIP      10.145.0.1       <none>                                   443/TCP          5d19h
sub-test        ClusterIP      10.145.120.194   <none>                                   80/TCP           8h
ngxslb2         ClusterIP      10.145.209.32    <none>                                   9090/TCP         6h36m
testing         ClusterIP      10.145.240.169   <none>                                   80/TCP           3h2m
earth-service   LoadBalancer   10.145.7.61      192.168.1.91,192.168.1.93,192.168.1.95   8080:32753/TCP   19m


--> export service.
walter@k3-subctl-m1:~$ subctl export service --kubeconfig kubeconfig.cluster-b --namespace default earth-service
Service exported successfully


--> Check service exports in cluster b.
walter@k3-subctl-m1:~$ kubectl  --kubeconfig kubeconfig.cluster-b get serviceexports
NAME            AGE
sub-test        8h
ngxslb2         7h10m
earth-service   98s

--> Check service import in cluster a.  But, does not see earth-service. 
walter@k3-subctl-m1:~$ kubectl  --kubeconfig kubeconfig.cluster-a get -n submariner-operator serviceimport
NAME                         TYPE           IP                   AGE
sub-test-default-cluster-b   ClusterSetIP   ["10.145.120.194"]   8h
ngxslb2-default-cluster-b    ClusterSetIP   ["10.145.209.32"]    6h35m


```

**Comment by nyechiel** [comment]
@cwalterhk can you explain what's your motivation/use case here? A LoadBalancer type service should have externally-accessible IP address, so what's the point in exporting it?

**Comment by ccwalterhk** [comment]
I was referring to export to another cluster, not to export externally.  If I have loadbalaner type service and I would like to export to another cluster via submariner.

**Comment by nyechiel** [comment]
> I was referring to export to another cluster, not to export externally. If I have loadbalaner type service and I would like to export to another cluster via submariner.

Yes, I understand that. But if you have a LoadBalancer type service, it means that you want it be accessible from the outside to begin with - so what's the point/benefit in using Submariner?

@skitt @vthapar @aswinsuryan looking at https://github.com/kubernetes/enhancements/tree/master/keps/sig-multicluster/1645-multi-cluster-services-api#clusterset-service-behavior-expectations - should we do anything to support NodePort and LoadBalancer type services?

**Comment by aswinsuryan** [comment]
> > I was referring to export to another cluster, not to export externally. If I have loadbalaner type service and I would like to export to another cluster via submariner.
> 
> Yes, I understand that. But if you have a LoadBalancer type service, it means that you want it be accessible from the outside to begin with - so what's the point/benefit in using Submariner?
> 
> @skitt @vthapar @aswinsuryan looking at https://github.com/kubernetes/enhancements/tree/master/keps/sig-multicluster/1645-multi-cluster-services-api#clusterset-service-behavior-expectations - should we do anything to support NodePort and LoadBalancer type services?

@nyechiel yes, for spec compliance we need support for both LoadBalancer and NodePort type services. We started with clusterIP services and didn't expand it since we didn't have a real use case.

**Comment by ccwalterhk** [comment]
Hi both, I was just doing the testing.  But, maybe we don't have use case.   I was just wondering.  Even it can access externally. Sometimes, we may still want to access via "internal".

**Comment by mkolesnik** [comment]
On LB type service the IP is external to the cluster no? So how would that work if let's say a packet arrives to the cluster with dest IP of the LB service, would the CNI/K8s on the dest cluster know how to deal with that?

As for NodePort we can expose the nodes subnet as well but that just increases the possibility of CIDR collision, I suggest we stick with ClusterIP services as its the most beneficial.

**Comment by dfarrell07** [comment]
If this is still needed/relevant feel free to re-open, otherwise cleaning up for now.
