### ISSUE TITLE
DNS resolution sometimes does not work. 

### ISSUE THREAD

**Issue by ccwalterhk** [submariner-io/lighthouse#663]
**What happened**: DNS resolution sometimes not working. This is even within cluster (not across cluster yet). 

Example.  ngxslb2 is service. When I login into container and do curl. sometimes, I can get response "Hello Kubernetes!" and sometimes, I could not.
```
walter@k3-subctl-m1:~$ kubectl --kubeconfig kubeconfig.cluster-b get service
NAME         TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
kubernetes   ClusterIP   10.145.0.1       <none>        443/TCP    5d17h
sub-test     ClusterIP   10.145.120.194   <none>        80/TCP     6h35m
ngxslb2      ClusterIP   10.145.209.32    <none>        9090/TCP   4h23m
testing      ClusterIP   10.145.240.169   <none>        80/TCP     49m
walter@k3-subctl-m1:~$ 


bash-5.1# curl ngxslb2:9090
Hello Kubernetes!
bash-5.1# 
bash-5.1# 
bash-5.1# curl ngxslb2.default.svc.cluster.local:9090
Hello Kubernetes!
bash-5.1# 
bash-5.1# 
bash-5.1# curl ngxslb2.default.svc.cluster.local.:9090
Hello Kubernetes!
bash-5.1# curl ngxslb2.default.svc.cluster.local.:9090
Hello Kubernetes!
bash-5.1# curl ngxslb2.default.svc.cluster.local:9090
Hello Kubernetes!
bash-5.1# curl ngxslb2.default.svc.cluster.local.:9090.   <--- put a . at the end of FQDN.
Hello Kubernetes!
bash-5.1# curl ngxslb2.default.svc.cluster.local:9090
curl: (6) Could not resolve host: ngxslb2.default.svc.cluster.local
bash-5.1# 
bash-5.1# 

```

**What you expected to happen**:  DNS resolution should be working all the time.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):

```
walter@k3-subctl-m1:~$ subctl --kubeconfig kubeconfig.cluster-b diagnose all
Cluster "default"
 ✓ Checking Submariner support for the Kubernetes version
 ✓ Kubernetes version "v1.22.5+k3s1" is supported

 ✓ Checking Submariner support for the CNI network plugin
 ✓ The detected CNI network plugin ("generic") is supported

 ✓ Checking gateway connections
 ✓ All connections are established

 ✓ Checking Submariner pods
 ✓ All Submariner pods are up and running
 ⚠ Pod "submariner-gateway-zqcvr" has restarted 8 times

 ✓ Non-Globalnet deployment detected - checking if cluster CIDRs overlap
 ✓ Clusters do not have overlapping CIDRs

 ✓ Checking Submariner support for the kube-proxy mode 
 ✓ The kube-proxy mode is supported

 ✗ Checking the firewall configuration to determine if the metrics port (8080) is allowed 
 ✗ The tcpdump output from the sniffer pod does not contain the client pod HostIP. Please check that your firewall configuration allows TCP/8080 traffic on the "k3-subctl-w2" node.

 ✓ Checking the firewall configuration to determine if VXLAN traffic is allowed 
 ✓ The firewall configuration allows VXLAN traffic

Skipping inter-cluster firewall check as it requires two kubeconfigs. Please run "subctl diagnose firewall inter-cluster" command manually.

```

- Gather information (use `subctl gather`):

[submariner-20211231080634.tar.gz](https://github.com/submariner-io/submariner/files/7795649/submariner-20211231080634.tar.gz)

- Cloud provider or hardware configuration: 
- Install tools:
- Others:

**Comment by nyechiel** [comment]
@cwalterhk did you manage to figure it out?

**Comment by ccwalterhk** [comment]
Based on my last finding, it seems to be a bug.

**Comment by nyechiel** [comment]
Since you see the issue even with `cluster.local` I find it hard to believe that it has to do with Submariner. @aswinsuryan can you please take a look and see if anything here rings a bell?

**Comment by aswinsuryan** [comment]
@nyechiel Yes that is right, Submariner does is responsible only for request that comes on clusterset.local. The in-cluster coredns does not forward request for other domain names to submariner coreDNS.

@cwalterhk Do you face this issue only when submariner is deployed?

**Comment by ccwalterhk** [comment]
I have two sets of K3S cluster.  One without Submariner. Another one has submariner installed.   The one without submariner does not have the problem.

**Comment by ccwalterhk** [comment]
I did not do the test before installing submariner.

**Comment by aswinsuryan** [comment]
Closing for now due to lack of information.
