### ISSUE TITLE
Remote service is not available if namespace is deleted and recreated

### ISSUE THREAD

**Issue by davidohana** [submariner-io/lighthouse#685]
**What happened**:

1. Export service `my-svc` on namespace `my-ns` on `cluster1`
2. Create namespace `my-ns` on `cluster2`
3. LH agent creates `endpointslice` on `my-ns` at `cluster2` 
4. `my-svc` is now accessible on cluster2 at endpoint `my-svc.my-ns.svc.clusterset.local`
5. Delete namespace `my-ns` on `cluster2`
6. Create namespace `my-ns` on `cluster2`

**What you expected to happen**:
`endpointslice` shall be recreated once namespace is recreated.
In practice, it is not created again and remote service is not available

**Anything else we need to know?**:
If LH agent is restarted, `endpointslice` is downloaded from broker and situation is fixed.

**Comment by vthapar** [comment]
Currently we don't check or track namespace on imported clusters. Fix for #605 should make sure this use case is also handled.

**Comment by dfarrell07** [comment]
This may be related to https://github.com/submariner-io/submariner/issues/1734, maybe even a partial duplicate.
