### ISSUE TITLE
Initialise the Lighthouse metrics to zero

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/lighthouse#704]
Currently, Lighthouse exports the following metrics `submariner_service_import`, `submariner_service_export` and `submariner_service_discovery_query`. However, these metrics will be visible in the dashboard only when we create a ServiceExport or if there is a ServiceImport in the Cluster. 

When a user tries to query for these metrics before creating the serviceExport, it results into an error.

It would be friendlier if we initialise these metrics to zero as part of LH boot-up and reconcile them to their proper values once the caches are synced.

**Comment by vthapar** [comment]
All lighthouse metrics are handled in syncer code in Admiral:

https://github.com/submariner-io/admiral/blob/devel/pkg/syncer/resource_syncer.go#L434
https://github.com/submariner-io/admiral/blob/devel/pkg/syncer/resource_syncer.go#L485

This will require changes in Admiral to provide an API to initialize metrices. This will impact other code that relies on Admiral for metrices too. Likely not an issue yet coz ServiceImport/Export are only ones that don't get autocreated and synced at init, but are user driven.

**Comment by maayanf24** [comment]
The challenge here is to set in advance the metric with it's relevant labels.
For example, you cannot know at boot time what will be the destination service name, which is one of the labels for `submariner_service_discovery_query`.

**Comment by vthapar** [comment]
These can be initalized to zero at init coz these are aggregate and 0 means none created `submariner_service_import` `submariner_service_export`.

`submariner_service_discovery_query` can't be initialized to zero coz it is tied to each individual instance of service being exported. It should be initialized to zero when service export is created and we add labels to it.

@sridhargaddam @maayanf24 Makes sense? Or did I misunderstand these metrices?

**Comment by nyechiel** [comment]
@maayanf24 what's the user impact here? should we just close it?

**Comment by maayanf24** [comment]
I think it the effort to fix is more then the user impact. Since no user asked to fix this, I think it can be closed for now
