### ISSUE TITLE
Use nginx rootless  "quay.io/openshifttest/nginx-alpine:latest"

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/lighthouse#734]
We should rather use `quay.io/openshifttest/nginx-alpine:latest` image - which is rootless - instead of "quay.io/testing-farm/nginx:latest", otherwise our e2e will keep failing on OCP clusters.

_Originally posted by @dfarrell07 in https://github.com/submariner-io/lighthouse/issues/731#issuecomment-1106581019_

**Comment by dfarrell07** [comment]
We need a rootless nginx container, but IDK if that one is a good solution. It doesn't seem to have been updated in 2y.

https://quay.io/repository/openshifttest/nginx?tab=tags

I would love to get the test-farm folks to mirror the official non-root nginx container from DockerHub to Quay.

**Comment by manosnoam** [comment]
@dfarrell07 
[quay.io/openshifttest/nginx-alpine:latest](http://quay.io/openshifttest/nginx-alpine:latest) is from Fri, Sep 24, 2021 10:15 AM, not so long ago

**Comment by skitt** [comment]
> Fri, Sep 24, 2021 10:15 AM, not so long ago

But still far too long ago: https://quay.io/repository/openshifttest/nginx-alpine/manifest/sha256:0d97a01288e1b0395cbcba653f1491aa9e10582b87fee254d7fbe59e834ecaae?tab=vulnerabilities (this isn’t the exact same image, but the `:latest` image is based on the same Alpine image and will have the same vulnerabilities).

**Comment by dfarrell07** [comment]
We use the nettest image now, so I think this can be closed.
