### ISSUE TITLE
Lighthouse-controller is not reachable between private and public clusters

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/lighthouse#74]
Installing Submariner with service-discovery on OSP (private cluster) and AWS (public cluster), the lighthouse-controller seems to be unreachable between clusters:

Testing connection between ngnix <--> netshoot works with direct IPs, but does not work with domain name:
```
export KUBECONFIG=/home/nmanos/automation/ocp-install/nmanos-cluster-a/auth/kubeconfig
/home/nmanos/automation/ocp-install/oc exec netshoot-58785d5fc7-82kc7 -- curl --output /dev/null  --verbose --head --fail 100.96.144.67
*   Trying 100.96.144.67:80...
* TCP_NODELAY set
* Connected to 100.96.144.67 (100.96.144.67) port 80 (#0)
> HEAD / HTTP/1.1
> Host: 100.96.144.67
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: nginx/1.17.8
< Date: Thu, 12 Mar 2020 12:56:09 GMT
< Content-Type: text/html
< Content-Length: 612
< Last-Modified: Tue, 21 Jan 2020 14:39:00 GMT
< Connection: keep-alive
< ETag: "5e270d04-264"
< Accept-Ranges: bytes
< 
* Connection #0 to host 100.96.144.67 left intact
nginx_service_cluster_b=nginx-demo
# Nginx service on Cluster B, will be identified by its Domain Name (with --service-discovery): nginx-demo
/home/nmanos/automation/ocp-install/oc exec netshoot-58785d5fc7-82kc7 -- curl --output /dev/null -m 30 --verbose --head --fail nginx-demo
* Could not resolve host: nginx-demo                                          
* Closing connection 0
curl: (6) Could not resolve host: nginx-demo
command terminated with exit code 6
```

Lighthouse pod log shows:

`{Name:"nmanos-cluster-b-tunnel-jsvwf"}}, Status:v1beta1.KubeFedClusterStatus{Conditions:[]v1beta1.ClusterCondition{v1beta1.ClusterCondition{Type:"Offline", Status:"True", LastProbeTime:v1.Time{Time:time.Time{wall:0x0, ext:63719526907, loc:(*time.Location)(0x1dc4b60)}}, LastTransitionTime:v1.Time{Time:time.Time{wall:0x0, ext:63719526907, loc:(*time.Location)(0x1dc4b60)}}, Reason:"ClusterNotReachable", Message:"cluster is not reachable"}}, Zones:[]string(nil), Region:""}}`

[submariner_downstream_11032020_1341.log](https://github.com/submariner-io/lighthouse/files/4318477/submariner_downstream_test_11032020_1341.log)

**Comment by vthapar** [comment]
Not applicable anymore with removal of kubefed dependency.

**Comment by manosnoam** [comment]
Agree
