### ISSUE TITLE
Service labels not captured in Endpointslices generated from lighthouse agent

### ISSUE THREAD

**Issue by abguptms** [submariner-io/lighthouse#754]
**What happened**:
The endpointslices.discovery.k8s.io/v1 document generated by lighthouseagent for an exported service lacks the labels associated with the actual service document.
**What you expected to happen**:
Alike EndpointController which actually maps all the labels associated with the actual service document, expectation is that the endpointslices generated from submariner too captures all the service level labels.
**How to reproduce it (as minimally and precisely as possible)**:
Add a custom label to a service document e.g. reprolabel: reprovalue
Export the service and check all the endpointslices in the cluster.
Compare the labels of the endpointslice document generated by endpointcontroller vs lighthouse agent. Former will contain the new label.
**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`)
- Cloud provider or hardware configuration:
- Install tools:
- Others:
[endpointcontroller-slices.txt](https://github.com/submariner-io/submariner-operator/files/8663311/endpointcontroller-slices.txt)
[submariner-slices.txt](https://github.com/submariner-io/submariner-operator/files/8663312/submariner-slices.txt)

**Comment by dfarrell07** [comment]
Thanks for the report (and sorry to be slow getting back with you)! As we try to prioritize this, we're interested in the use-case folks have for this. Why is this useful for you? If the reason is to be similar to EndpointController, we don't think we want to mirror that behavior exactly because this is a multi-cluster context, and syncing all labels would be a lot of traffic and potential conflicts. But if you have use case other than parity, please let us know!

**Comment by abguptms** [comment]
We have the following few scenarios where we need further labels on our endpointslices to pick the right set of endpoints:
1. We have a custom routing layer which looks at endpoints to decide which routing class is to be used. This information is captured as a label by each Service and is replicated by EndpointController on endpoints/endpointslices. However, submariner slices don't capture these custom labels and we can't detect this information at the endpointslice level. We don't read any other documents for this information as that would consume unnecessary resources. 
2. Another routing layer scenario for us to create weighted routing traffic manager endpoints for our downstream services. However, the naming for those is currently fixed to use service document name due to missing labels in endpointslices. We need functionality to customize those names (its lower priority but would be good to have for us).

I believe identifying custom labels vs endpoint controller generated labels might be tricky. For this, could we implement class of label(s) under lighthouse category to be picked and added to the endpointslices? Something like:
lighthouse.submariner.io/custom: "<json object>" or lighthouse code and put any label we create using this category.

**Comment by vthapar** [comment]
@abguptms How about adding labels to serviceExport and have those added to EndpointSlices created by Lighthouse? I think this works better coz ServiceExport => LH EndpointSlice is a better multicluster analog of Service => EP Controller Slice.

It should be easy enough to write tooling/script to copy over Service labels to ServiceExport. This also gives freedom to select which labels need to be multicluster as not all of them might be relevant or needed for a multicluster service.

**Comment by abguptms** [comment]
@vthapar, that sounds fair. We can use either Service or ServiceExport as both needs to be present together anyway for this purpose. I like the idea of specific labels being decided. 

Regarding tooling, will that be on the consumer side or lighthouse will auto add those based on whatever is available in ServiceExports. Modifying endpointslices between lighthouse and custom tooling is not something we look to implement. Open to further suggestions though.

**Comment by vthapar** [comment]
@abguptms Lihthouse will auto-add any labels present on service export. Tooling I metioned was for copying labels required over from Service to ServiceExport, which I agree should be  user side tooling.

**Comment by abguptms** [comment]
thanks for the clarification. Looks good to me. We will wait for this to be available in 0.16.

**Comment by tpantelis** [comment]
We now derive our `EndpointSlices` from the K8s `EndpointSlices` so we can inherit the labels, replacing the "_endpointslice.kubernetes.io/managed-by_" label with ours. K8s also adds the "_kubernetes.io/service-name_" label and in some cases a couple others starting with "_kubernetes.io_". To be safe, we could just omit all labels starting with "_kubernetes.io_".

**Comment by abguptms** [comment]
That would work. Our labels are custom and don't start with kubernetes.io. I suppose the information contained in kubernetes.io labels is already captured by Submariner using independent labels?

**Comment by tpantelis** [comment]
We only set "_endpointslice.kubernetes.io/managed-by_" and a couple "_multicluster.kubernetes.io/*_" labels in addition to our own.
