### ISSUE TITLE
EndpointSlices generated by lighthouse agent doesn't capture all endpoint conditions 

### ISSUE THREAD

**Issue by abguptms** [submariner-io/lighthouse#755]
**What happened**:
The endpointslices generated by submariner-operator don't capture all the conditions associated with an endpoint. Only ready condition is captured while serving and terminating are not captured.
**What you expected to happen**:
All the conditions associated with an endpoint should be captured. All conditions including ready, serving and terminating.
**How to reproduce it (as minimally and precisely as possible)**:
Check endpointslices generated for any exported service and compare it with the endpointslices generated by endpointscontroller.
**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`)
- Cloud provider or hardware configuration:
- Install tools:
- Others:
[endpointcontroller-slices.txt](https://github.com/submariner-io/submariner-operator/files/8663348/endpointcontroller-slices.txt)
[submariner-slices.txt](https://github.com/submariner-io/submariner-operator/files/8663349/submariner-slices.txt)

**Comment by dfarrell07** [comment]
I think there were some improvements in these statues, but I'm not sure it's exactly this request. CC @aswinsuryan volunteered to check.

**Comment by tpantelis** [comment]
`Serving` and `Terminating`  are condition states associated with `EndpointSlice` endpoints. Currently we derive our multi-cluster `EndpointSlices` from the legacy `EndPoints` resource which contains only "ready" and "not ready" endpoint addresses.  I assume the `EndpointSlice` `Serving` and `Terminating` states are considered "not ready". That said, we plan to convert to deriving our `EndpointSlices` from the K8s `EndpointSlices`, at which time we can consider propagating `Serving` and `Terminating` endpoint addresses.
