### ISSUE TITLE
Skip local endpoint slice lookup if not using globalnet

### ISSUE THREAD

**Issue by mikenorgate** [submariner-io/lighthouse#775]
#757 introduces functionality to lookup the local endpoint slice when using globalnet, when globalnet is not used this call is unnecessary and should be skipped to improve stability.

This requires lighthouse to be aware the globalnet is being used

**Comment by dfarrell07** [comment]
@mikenorgate are you up for working on this? @vthapar is willing to guide.

**Comment by dfarrell07** [comment]
This is the optimization in question: https://github.com/submariner-io/lighthouse/pull/757/files#diff-bb180bd8e9d88ab9707d01237c28f6f4732a69658881af60094bb9df2fc9317dR125
