### ISSUE TITLE
The Lighthouse CoreDNS plugin needs to switch to NormalizeExact

### ISSUE THREAD

**Issue by skitt** [submariner-io/lighthouse#779]
The plugin is now showing a warning:

```
Warning:  An external plugin (github.com/submariner-io/lighthouse/coredns/plugin/setup.go line 130) is using the deprecated function Normalize. This will be removed in a future versions of CoreDNS. The plugin should be updated to use OriginsFromArgsOrServerBlock or NormalizeExact instead.
```

See https://pkg.go.dev/github.com/coredns/coredns/plugin#Host.Normalize

**Comment by nyechiel** [comment]
@skitt @vthapar how important this one is? should we address in 0.14?

**Comment by tpantelis** [comment]
> @skitt @vthapar how important this one is? should we address in 0.14?

If I may, this is simple tech debt - I'll take it.
