### ISSUE TITLE
Aligning lighthouse CRDs with upstream design CRDs on multi cluster CRDs,

### ISSUE THREAD

**Issue by aswinsuryan** [submariner-io/lighthouse#78]
Aligning lighthouse CRDs with upstream design[1] CRDs on multi cluster CRDs and do the required changes in lighthouse controller to match the design proposal
[1] https://docs.google.com/document/d/1hFtp8X7dzVS-JbfA5xuPvI_DNISctEbJSorFnY-nz6o/edit

**Comment by nyechiel** [comment]
@vthapar @aswinsuryan is there anything that needs to be done here, or can we consider it done at this point?

**Comment by aswinsuryan** [comment]
> @vthapar @aswinsuryan is there anything that still needs to be done here, or can we consider it done at this point?

@nyechiel We have a few more items that we have added in 0.7.0 project board. And given that we are now very close to the upstream proposal, we are also thinking if we could add a mode (like --kubeproxy) which would make it exactly as in the proposal and can be consumed when the kube-proxy changes are ready.

So I think, we can keep this open until we finish of these tasks

**Comment by nyechiel** [comment]
This is done at this point. Last final bit is being tracked here: https://github.com/submariner-io/lighthouse/issues/336
