### ISSUE TITLE
[Lighthouse] Flake Finder: globalnet, helm, 1.23 job is failing 

### ISSUE THREAD

**Issue by nyechiel** [submariner-io/lighthouse#787]
See https://github.com/submariner-io/lighthouse/actions/runs/2607136964 and https://github.com/submariner-io/lighthouse/actions/runs/2603270739

**Comment by nyechiel** [comment]
@aswinsuryan can you please take a look at this?

**Comment by aswinsuryan** [comment]
The test seems to be taking so much time , though it is not consistent with all runs, This should be related to infra, like some pod is not coming to the available state in a short time.

**Comment by nyechiel** [comment]
> The test seems to be taking so much time , though it is not consistent with all runs, This should be related to infra, like some pod is not coming to the available state in a short time.

@aswinsuryan @skitt I noticed that the latest Release Images job was failing in Lighthouse for devel: https://github.com/submariner-io/lighthouse/runs/7111496378?check_suite_focus=true

Could it be related?

**Comment by skitt** [comment]
I doubt it, the release failure was caused by a Golang proxy error. The stale images wouldn’t cause problems because the last merge in `devel` was an infrastructure fix; nothing changed in the images.

**Comment by dfarrell07** [comment]
The Flake Finder has been passing for the last weekish 100%.

https://github.com/submariner-io/lighthouse/actions/workflows/flake_finder.yml
