### ISSUE TITLE
Figure out what to do about GHSA-2927-hv3p-f3vp in caddy

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/lighthouse#813]
The [proposed Anchore vulnerability scanning is flagging this](https://github.com/submariner-io/lighthouse/runs/7291951221?check_suite_focus=true).

It seems to be an issue in [caddyserver/caddy](https://github.com/caddyserver/caddy) and is fixed in the recent releases.

However, we use a [stripped-down fork of caddy v1](https://github.com/coredns/caddy), specialized for use in coredns. It pulls in caddy 1.0.5, which I guess doesn't have the fix (should confirm).

We should check if coredns/caddy is exposed to the vuln. It may not pull in the relevant code or have been patched.

**Comment by dfarrell07** [comment]
Any thoughts, @skitt?

**Comment by skitt** [comment]
It turns out `coredns/caddy` _doesn’t_ pull in `caddyserver/caddy`; the latter is pulled in by Lighthouse because our CoreDNS plugin imports its `onevent` package. `coredns/caddy` has its own implementation of `onevent`, so if we use that we can drop our `caddyserver/caddy` dependency entirely.

**Comment by skitt** [comment]
`coredns/caddy` doesn’t include the `caddyhttp` module which is [where the vulnerability lies](https://github.com/caddyserver/caddy/pull/4407) (see also [the followup](https://github.com/caddyserver/caddy/pull/4499) which is the GHSA being discussed here).
