### ISSUE TITLE
globalIP for headless service without selector needs to be set to Endpointslice

### ISSUE THREAD

**Issue by mkimuram** [submariner-io/lighthouse#817]
**What happened**:
GlobalIP isn't set to Endpointslice when headless service without selector is created.

**What you expected to happen**:
GlobalIP is set to Endpointslice when headless service without selector is created.

**How to reproduce it (as minimally and precisely as possible)**:

Follow the steps until "Verify access to External hosts from clusters" in https://github.com/submariner-io/submariner-website/pull/797 .
And check Endpointslice for the endpoint.

**Anything else we need to know?**:

Current [code](https://github.com/submariner-io/lighthouse/blob/devel/pkg/agent/controller/endpoint.go#L278) only handle the case that endpoints are for pod. For headless service without selector in globalnet, it needs to also handle the case that endpoints are created by users.

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by dfarrell07** [comment]
Once this is fixed, we should revisit the Know Issue https://github.com/stolostron/backlog/issues/26901 and then discuss QE coverage.

**Comment by dfarrell07** [comment]
We're looking for someone else to adopt this code, drive it over the finish line. :pray: :pleading_face: 

If we don't find someone in the next stalebot cycle, I think we should close this. We can always re-open if there's interest.
