### ISSUE TITLE
Helm+Lighthouse jobs are failing

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/lighthouse#888]
There seems to be consistent failures in some parts of the CI matrix that combine Lighthouse and Helm.

On the Lighthouse repo:
[E2E (helm, 1.25)](https://github.com/submariner-io/lighthouse/actions/runs/3193870523/jobs/5212868250#logs)
[E2E (globalnet, helm, 1.25)](https://github.com/submariner-io/lighthouse/actions/runs/3193870523/jobs/5212868382#logs)

On the Helm repo:
[E2E (libreswan, globalnet, 1.25, lighthouse)](https://github.com/submariner-io/submariner-charts/actions/runs/3182680207/jobs/5205529511#logs)
[E2E (wireguard, globalnet, 1.25, lighthouse)](https://github.com/submariner-io/submariner-charts/actions/runs/3182680207/jobs/5205530164#logs)

However, some jobs with Helm and Lighthouse are passing. Helm repo:
[E2E (vxlan, 1.25, lighthouse)](https://github.com/submariner-io/submariner-charts/actions/runs/3182680207/jobs/5205530544#logs)
[E2E (vxlan, globalnet, 1.25, lighthouse)](https://github.com/submariner-io/submariner-charts/actions/runs/3182680207/jobs/5205530954#logs)
[E2E (libreswan, 1.25, lighthouse)](https://github.com/submariner-io/submariner-charts/actions/runs/3182680207/jobs/5205529240#logs)

**Comment by sridhargaddam** [comment]
All jobs seem to be passing now in Lighthouse repo:
https://github.com/submariner-io/lighthouse/actions/runs/3212460031
