### ISSUE TITLE
Update the lighthouse documentation

### ISSUE THREAD

**Issue by aswinsuryan** [submariner-io/lighthouse#91]
Update the lighthouse documentation with the new architecture.

**Comment by nyechiel** [comment]
This needs to be updated to reflect the new architecture: https://submariner-io.github.io/architecture/components/lighthouse/

**Comment by aswinsuryan** [comment]
Have raised PR's on the respective projects as below
submariner-operator/pull/334 ,
submariner-io/lighthouse/pull/100 ,
submariner-website/pull/94 , 
submariner-website/pull/92,
