### ISSUE TITLE
First packet only: Destination host unreachable

### ISSUE THREAD

**Issue by s-mansouri** [submariner-io/lighthouse#934]
**What happened**:
I have two cluster with kube-ovn CNI. I connect this two clusters with submariner based on this [doc](https://github.com/kubeovn/kube-ovn/blob/v1.10.6/docs/cluster-submariner.md).
**cluster k8sfo02**
```
subctl deploy-broker
subctl join broker-info.subm --clusterid  k8sfo02 --clustercidr 11.17.0.0/16  --natt=false --cable-driver vxlan --health-check=false
```

**cluster k8sfo01**
```
subctl join broker-info.subm --clusterid  k8sfo01 --clustercidr 12.16.0.0/16  --natt=false --cable-driver vxlan --health-check=false
```
But when I ping the IP pod of another cluster from local cluster, only first packet reaches, after that it gives Destination Host Unreachable
```
k8sfo02:~# ping 12.16.0.7
PING 12.16.0.7 (12.16.0.7) 56(84) bytes of data.
From 241.32.21.236 icmp_seq=1 Destination Host Unreachable
From 241.32.21.236 icmp_seq=2 Destination Host Unreachable
From 241.32.21.236 icmp_seq=3 Destination Host Unreachable
```

**Environment**:
- Diagnose information (use `subctl diagnose all`):
```
Cluster "k8sfo01"
 ✓ Checking Submariner support for the Kubernetes version
 ✓ Kubernetes version "v1.25.2" is supported

 ⚠ Checking Submariner support for the CNI network plugin
 ⚠ Submariner could not detect the CNI network plugin and is using ("generic") plugin. It may or may not work.
 ✓ Trying to detect the Calico ConfigMap 

 ✓ Checking gateway connections
 ✓ All connections are established

 ✓ Non-Globalnet deployment detected - checking if cluster CIDRs overlap
 ✓ Clusters do not have overlapping CIDRs
 ✓ Checking Submariner pods 
 ✓ All Submariner pods are up and running

 ✓ Checking Submariner support for the kube-proxy mode 
 ✓ The kube-proxy mode is supported

 ✓ Checking the firewall configuration to determine if the metrics port (8080) is allowed 
 ✓ Skipping this check as it's a single node cluster

 ✓ Checking the firewall configuration to determine if intra-cluster VXLAN traffic is allowed
 ✓ Skipping this check as it's a single node cluster

 ✓ Globalnet is not installed - skipping
```
- Gather information (use `subctl gather`):
[submariner-20221031062728.tar.gz](https://github.com/submariner-io/lighthouse/files/9898548/submariner-20221031062728.tar.gz)
[submariner-20221031062744.tar.gz](https://github.com/submariner-io/lighthouse/files/9898550/submariner-20221031062744.tar.gz)
- Cloud provider or hardware configuration:
Arvancloud
- Install tools:
install kubernetes cluster with Kubeadm
install submariner with subctl

**Comment by dfarrell07** [comment]
CC @aswinsuryan @sridhargaddam 

Thanks for the report, that's an interesting error!

**Comment by dfarrell07** [comment]
We support OVN-Kubernetes, but not kube-ovn. Does that work for you? Closing this for now, but feel free to reopen.
