### ISSUE TITLE
Synced endpointslice name in broker namespace missing original namespace name

### ISSUE THREAD

**Issue by abguptms** [submariner-io/lighthouse#957]
**What happened**:
We have two services under different namespace with same name. When we export them using lighthouse, it overwrites information from the last updated resource. This conflict affects our ability to run same name services under different namespaces.

**What you expected to happen**:
Namespace name attached to endpoint slice document name synced to broker namespace.

**How to reproduce it (as minimally and precisely as possible)**:
1. Setup a broker and agent cluster.
2. Setup nginx service in agent cluster under temp namespace using following commands
   1. kubectl create namespace temp
   2. kubectl create deployment nginx -n temp --image=nginx
   3. kubectl expose deployment nginx -n temp --port=80
   4. subctl export service nginx
3. Check synced document for nginx under broker namespace. It should show endpoints from **nginx under temp** namespace.
4. Follow all the steps from step 2 under namespace demo.
5. Check synced document for nginx under broker namespace. It should show endpoints from **nginx under demo** namespace.
7. Scale nginx deployment under temp namespace by executing "kubectl scale deployment nginx -n temp --replicas=2"
8. Check synced document for nginx under broker namespace. It should show endpoints from **nginx under temp** namespace

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by dfarrell07** [comment]
This seems to be related to https://github.com/submariner-io/lighthouse/issues/214.

**Comment by abguptms** [comment]
No, the issue here is that the name of the document synced under broker namespace doesn't contain namespace which conflicts with any other same name application under a different namespace.

Issue 214 is aggregating all the serviceimports from all lighthouse agents under a single document. These are very different problems. My issue will still persist even if aggregated under a name only based document since we can have same name applications under different customer namespaces.

My understanding is these lines: [line1](https://github.com/submariner-io/lighthouse/blob/9fdff05fdc3c3365d3bc98097ad507a1369f8f3d/pkg/agent/controller/endpoint.go#L134), [line2](https://github.com/submariner-io/lighthouse/blob/9fdff05fdc3c3365d3bc98097ad507a1369f8f3d/pkg/agent/controller/endpoint.go#L161) need to include endpoints.Metadata.Namespace.

endpointSliceName := endpoints.Metadata.Namespace + "-" + endPoints.Metadata.Name + "-" + e.clusterID

**Comment by skitt** [comment]
@abguptms the problems are different, yes; but from our perspective fixing #214 would also fix this.

**Comment by abguptms** [comment]
Okay, sounds good. I can track issue [#214](https://github.com/submariner-io/lighthouse/issues/214) if we want to mark this as duplicate.

**Comment by tpantelis** [comment]
I don't think https://github.com/submariner-io/lighthouse/issues/214 would inherently fix this. Looking at the [enhancement proposal](https://github.com/submariner-io/enhancements/pull/111/files), the `EndpointSlice` functionality would largely remain the same. I think the problem here is that we don't include the namespace in the [EndpointSlice  name](https://github.com/submariner-io/lighthouse/blob/9fdff05fdc3c3365d3bc98097ad507a1369f8f3d/pkg/agent/controller/endpoint.go#L161) as we do for [ServiceImport](https://github.com/submariner-io/lighthouse/blob/9fdff05fdc3c3365d3bc98097ad507a1369f8f3d/pkg/agent/controller/agent.go#L514).
