### ISSUE TITLE
MCS conformance: ServiceImports should have a single IP address

### ISSUE THREAD

**Issue by skitt** [submariner-io/lighthouse#980]
The MCS API spec says

> A non-headless `ServiceImport` is expected to have an associated IP address, the clusterset IP, which may be accessed from within an importing cluster. This IP may be a single IP used clusterset-wide or assigned on a per-cluster basis, but is expected to be consistent for the life of a `ServiceImport` from the perspective of the importing cluster. Requests to this IP from within a cluster will route to backends for the aggregated Service.

The conformance test checks for this and fails on Submariner.

Where possible (_i.e._ when using Globalnet), `ServiceImport` objects should reflect the global IP address for the service.

**Comment by tpantelis** [comment]
> The conformance test checks for this and fails on Submariner.

I'm not really clear on this. Does the conformance test check that the [ServiceImport .Spec.IPs](https://github.com/kubernetes-sigs/mcs-api/blob/670de427cbd95227df903dd2b053414e3546aede/pkg/apis/v1alpha1/serviceimport.go#L58) field has a single entry in the array? We are [compliant](https://github.com/submariner-io/lighthouse/blob/c02c67a3b96f947a1c6df70052dcf8367d9cbe47/pkg/agent/controller/agent.go#L315) with this. 

> Where possible (i.e. when using Globalnet), ServiceImport objects should reflect the global IP address for the service.

hmm... we do set the [global IP address](https://github.com/submariner-io/lighthouse/blob/c02c67a3b96f947a1c6df70052dcf8367d9cbe47/pkg/agent/controller/agent.go#L313).

Or does it fail b/c we don't aggregate the `ServiceImport`s and assign a single clusterset-wide VIP? If so, this part of the spec seems to contradict that "_This IP may be a single IP used clusterset-wide or **assigned on a per-cluster basis**_" - we do the latter. Unless I'm missing something or misinterpreted something...

**Comment by tpantelis** [comment]
Looking at the [MCS test code](https://github.com/kubernetes-sigs/mcs-api/blob/master/e2etest/connectivity_test.go), my guess is that this check failed:

```
Eventually(func() []string {
    svcImport, err := cluster1.mcs.MulticlusterV1alpha1().ServiceImports(namespace).Get(ctx, helloServiceImport.Name, 
metav1.GetOptions{})
    Expect(err).ToNot(HaveOccurred())
    return svcImport.Spec.IPs
}).ShouldNot(BeEmpty())
```

The test setup actually creates the `ServiceImport` and apparently expects the MCS implementation to populate the `ServiceImport` IP.  But **lighthouse**  triggers off a `ServiceExport`  to create the `ServiceImport` - they're assuming there's a component that monitors and processes  `ServiceImport`s even w/o a `ServiceExport`.  The test setup should create a  `ServiceExport`.  cc @aswinsuryan

**Comment by skitt** [comment]
Let’s pause this on our side, I’ll bring it up in the conformance test discussions in MCS. (The general expectation that `ServiceImport`s work without `ServiceExport`s is invalid).
