### ISSUE TITLE
Always return globalIP for an exported clusterIP service when using clusterset.local domain name

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/lighthouse#993]
**What happened**:

In the initial implementation of Globalnet (i.e., v1) the globalIPs associated with exported `clusterIPServices` were not routable within the local cluster. So, to support the use-case, when a **client from the local cluster** makes a DNS query to `<svc-name>.<namespace>.svc.clusterset.local` domain, we are currently returning the `clusterIP` instead of the `globalIP` associated with the service. 

With the newer implementation of Globalnet (i.e.,v2), for every exported `clusterIPService`, we can support connectivity to the `globalIP` even from the same cluster as well. 

**What you expected to happen**:
When a `clusterIPServices` is exported and a request is made to the `<svc-name>.<namespace>.svc.clusterset.local` domain from the local cluster, Lighthouse should return the `globalIP` associated with the exported service instead of returning the `clusterIP`.

**Comment by vthapar** [comment]
@sridhargaddam Can you confirm that Globalnet v2 only supports globalIP within cluster for `ClusterIP` services, not headless? Just want to confirm that #656 is still valid and we don't need to undo that one.

**Comment by sridhargaddam** [comment]
> @sridhargaddam Can you confirm that Globalnet v2 only supports globalIP within cluster for `ClusterIP` services, not headless? 

Correct. The globalIP is only reachable within the local cluster when its associated with the `ClusterIP` services and not for Headless Services.

**Comment by tpantelis** [comment]
> Correct. The globalIP is only reachable within the local cluster when its associated with the `ClusterIP` services and not for Headless Services.

@sridhargaddam Is it possible to make headless service IPs routable within the local cluster and, if so, are there plans to do so?

**Comment by sridhargaddam** [comment]
> > Correct. The globalIP is only reachable within the local cluster when its associated with the `ClusterIP` services and not for Headless Services.
> 
> @sridhargaddam Is it possible to make headless service IPs routable within the local cluster and, if so, are there plans to do so?

To support reachability to globalIPs associated with Headless Services from local cluster, it requires a major change and currently there are not plans (as well as a use-case).
